### ISSUE TITLE
Error while running scenario with av and drt

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#105]
Hello,
 I have a scenario which combines private taxi like service (av) and pooling service (drt) along with the conventional modes of car, pt, and walk. However I encounter a run time error caused due to an 'unregistered main mode: drt'. But the main mode drt is already defined in the config file.  The java run file, config file and the error file are attached. 

[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/3053986/logfileWarningsErrors.log)
[JavaRunfile.txt](https://github.com/matsim-org/matsim-code-examples/files/3053991/JavaRunfile.txt)

[Config.txt](https://github.com/matsim-org/matsim-code-examples/files/3053993/Config.txt)

Any help with resolving the error would be deeply appreciated. 
@ikaddoura @michalmac @jfbischoff

**Comment by jfbischoff** [comment]
Hi Jishnu,

your code currently only adds taxi mode to the scenario and no DRT, so that's why it won't work.

Try creating your controler using the DRT Controler creator like here
https://github.com/matsim-org/matsim-maas/blob/master/src/main/java/org/matsim/maas/drt/RunDoorToDoorDrtExample.java#L48

Technically, this should work now.

Alternatively, you may simply want to use several DRT operators, with one of them offering a service for single passengers only. 
See this class to see how such a thing works
https://github.com/matsim-org/matsim/blob/master/contribs/drt/src/main/java/org/matsim/contrib/drt/run/examples/RunMultiModeDrtExample.java

Cheers,
Joschka

**Comment by ghost** [comment]
Dear Joschka,
  Thank you for the reply. I tried creating the controller using the DRT controler creator as suggested. This time I get unregistered mode error for taxi (java and error
[Java file.txt](https://github.com/matsim-org/matsim-code-examples/files/3054926/Java.file.txt)
[logfileWarningsErrors.log](https://github.com/matsim-org/matsim-code-examples/files/3054927/logfileWarningsErrors.log)

 file attached). I have included both taxi and drt modules in the config group. Does it imply that drt and taxi cannot be simulated togehter for some reason?
I still have not tried the different DRT operators option. 

Regards,
Jishnu
