### ISSUE TITLE
VolumesAnalyzer for count the vehicles leave links

### ISSUE THREAD

**Issue by MadushaSammani** [matsim-org/matsim-code-examples#1060]
I am using a volume analyzer to find the volume for each link. This is the code I used.
```
public static void main(String[] args) {
        String networkFile =  "scenarios/network.xml";
        Config config = ConfigUtils.createConfig();
        config.network().setInputFile(networkFile);
        Scenario scenario = ScenarioUtils.loadScenario(config);
        Network network = scenario.getNetwork();
        final int timeBinSize=900;
        final int maxTime=2*3600;
        VolumesAnalyzer vAnalyzer = new VolumesAnalyzer(timeBinSize, maxTime, network);
        EventsManager event= EventsUtils.createEventsManager();
        event.addHandler(vAnalyzer);
        EventsUtils.readEvents(event, EventFiles);
        for (Id linkId : vAnalyzer.getLinkIds()) {
            int[] volume = vAnalyzer.getVolumesForLink(linkId);
            System.out.println(linkId.toString() + " : "  + Arrays.toString(volume));
        }
    }
```
As I understood, the length of the output array should be 8. But I got a 10-element array for each link. 
Example for an output: 
**Link 9998 : [128, 20, 122, 150, 93, 64, 56, 56, 0, 535]**

Could you please let me know why I am getting ten elements for output?

**Comment by mrieser** [comment]
VolumesAnalyzer uses the following code:

```java
this.maxSlotIndex = (this.maxTime / this.timeBinSize) + 1;
....
volumes = new int[this.maxSlotIndex + 1];
```

and 

```java
	private int getTimeSlotIndex(final double time) {
		if (time > this.maxTime) {
			return this.maxSlotIndex;
		}
		return ((int) time / this.timeBinSize);
	}
```

As maxTime = 7200 in your case, maxSlotIndex = 9. Slot 0 is for time 0...899.9, Slot 1 for 900...1799.9, ... Slot 7 for 6300...7199.9, and Slot 8 for for 7200...7200. If there are any linkLeaveEvents with time>7200, they will be counted in Slot 9.
Slot 0 to 9 gives you the 10 entries in your array.

I have to admit that we probably could change the code to handle the specified maxTime as exclusive, instead of inclusive, at least in the case when it is exactly a multiple of the binSize. (If maxTime is not a multiple of binSize, the current behavior makes more sense as the highest regular slot would not only cover 1 second).
