### ISSUE TITLE
Can matsim use vehicle OD matrix as input and do the DTA directly, instead of the "agent-based" fashion?

### ISSUE THREAD

**Issue by Brad-Liu** [matsim-org/matsim-code-examples#108]
Hi, i am new to MATSim. I am searching a solution to use vehicle OD matrix as the input, instead of generating the individual activities and plans in the "agent-based" fashion. Because all i have now is the OD matrix from the macroscopic model (with time-of-day distributions) and the network file (including necessary information about the road network, such as lanes, turning movements, traffic controls, etc..), Is it possible to let MATSim to read these data and do the simulation? It seems this is to use the powerful agent-based simulation tool in a truncated way (by inserting the input data into somewhere in the middle of the whole MATSim simulation flow chart) but is it possible to do this and  how? Can anybody help answer this?

**Comment by kainagel** [comment]
Dear Brad-Liu, 

you will have to generate an input file that roughly looks like this (see the initial chapters of [matsim.org/userguide](matsim.org/userguide)):
<person><plan>
   <act type="dummy" x="..." y="..." end_time="..." />
   <leg mode="car"/>
   <act type="dummy" x="..." y="..." />
</plan></person>
...
That is, you need to go through your OD matrix, and for each OD relation generate as many such trips as you have trips in that OD relation.

Material in [https://github.com/matsim-org/matsim-code-examples/tree/11.x/src/main/java/org/matsim/codeexamples/population](https://github.com/matsim-org/matsim-code-examples/tree/11.x/src/main/java/org/matsim/codeexamples/population) may help.  (That material currently has a lot of overlap; it will be condensed over the coming weeks; so please don't get confused.) . But you could also write this in python or matlab or ...

You can set for x and y the zone centroid (which will make the agents have some problems to enter the network), or better give them random positions the corresponding zone.

Make sure that you spread the departures (= activity end times) evenly throughout the validity of the OD matrix, otherwise you will get weird peaks in the simulation where lots of people depart at the same time.

We are a bit hesitant to provide methods for upstream demand generation because we have found that each individual situation is differentl

Best wishes

Kai

**Comment by Brad-Liu** [comment]
Thanks very much, Kai, your answer helps a lot.

**Comment by ghost** [comment]
Hello,
I'm interested to know if it worked this way (generating OD matrix instead of agent-based plans)?

Thank you
