### ISSUE TITLE
Show on via the status of taxis

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#144]
Hello,
I would like to know if it is possible to show up on via the status of the taxis, if they are doing an empty drive or occupied drive.

Thank you for your time.

**Comment by jfbischoff** [comment]
You can colour agents in VIA depending on their next Activity. This should do the trick.

**Comment by mrieser** [comment]
In the vehicles settings, there is a section "Attributes". There, click on "Add" and select "Vehicle Occupancy" (see attached screenshot).
After this, you get the occupancy as an additional vehicle attribute. I'm not sure how the taxis behave, most likely they will report "occupancy = 1" for empty vehicles, because they count the driver. But then they should report occupancy = 2 (or larger) when there are actually passengers.

![vehOccupancy](https://user-images.githubusercontent.com/1038453/59281296-5198cf80-8c67-11e9-934c-5f75eb1e8d3d.png)

**Comment by PlumeRoberts** [comment]
Thank you very much M.RIESER, it indeed works, but I did not have the expected result. I thought that having autonomous taxis implied not having a driver, but here, there isn't any taxis empty (= with not driver and no client). Why this representation including the driver ?

**Comment by jfbischoff** [comment]
Even AVs require a driver agent, this is originating from the vehicle-driver interaction in Matsim. 
What makes them AVs is possibly a different vehicle dynamics or service times.

In a way, imagine there's a robot turning the steering wheel and opening and closing doors for it's passengers 😊

**Comment by PlumeRoberts** [comment]
In like the idea, thank you. But an other question comes up to my mind. Looking at all the taxis moving, I always see taxis with 1 or 2 passengers, but never more. How can I "tell" to the taxis to work in a different way, taking multiple person if they are doing the same trip ? Or "tell" him to take new passengers on the way if they are going in the same destination or is on the right way ?

**Comment by jfbischoff** [comment]
You need to use the drt contribution, see matsim-maas for an example.
https://github.com/matsim-org/matsim-maas

Taxi is single passenger only.

**Comment by PlumeRoberts** [comment]
Thank you very much.
