### ISSUE TITLE
How is the speed of a vehicles determined ?

### ISSUE THREAD

**Issue by PlumeRoberts** [matsim-org/matsim-code-examples#158]
Hello,

I would like to know how the speed of a vehicle is determined. I know it is done using the capacity of the arc adn the number of vehicles, but how is it exactly done ? Is it linear, or is it following a curve or a mathematical function ?

Thank you for your time.

**Comment by mrieser** [comment]
Have a look at Chapter 1.3 in the [MATSim Book](www.matsim.org/the-book).
In short: vehicles try to travel with free speed along a link. They can leave a link if (a) they are up front of the queue, and (b) if their next link has space. Once a link becomes full (e.g. due to too much inflow compared to the outflow of a link), no more vehicles can enter a link, resulting in upstream vehicles having to wait and blocking other vehicles behind them on the link, resulting in longer travel times and thus lower speeds on that link.

**Comment by PlumeRoberts** [comment]
I see, so no curve is actually used, but I am wondering if this gives out results that are close to reality.

I've shown this way of working to my colleague, and he knows about transport modelization, while I don't.
What is puzzling us is the question to know if this way of `arcLength / arcFreeSpeed + waitTime` does represent the reality where the calculations are way different and not linear.

**Comment by kainagel** [comment]
Could you please have a look at Chapter 50 of https://matsim.org/the-book ?  (It is a short chapter.)  In order to get that "double queue" behavior, you would have to set, in the `qsim` section of the matsim config, `trafficDynamics` to `kinematicWaves`.  (It would actually be good if that was the default, but someone needs to take it on to adapt all regression tests that would fail then.)  My personal opinion is that the difference between `queue` and `kinematicWave` is not very large for the cases we typically look at, but that is just my personal opinion.  And at any rate, in all of our newer simulations we use `kinematicWaves`.
