### ISSUE TITLE
Cadyts PT calibration

### ISSUE THREAD

**Issue by ChristophTraf** [matsim-org/matsim-code-examples#161]
We are currently trying to calibrate the PT using CADYTS and have noticed that the simulated values in the count files (simCountCompar…) are always the same as the scaled simulated values, regardless from the scaling factor. Could it be that the scaling factor has no influence on the simulation?

**Comment by kainagel** [comment]
Dear Christoph, given that nobody seems to have experience with this, it seems that you will have to look into the code.  The cadyts infrastructure seems to hold together for car counts.  However, for pt counts the problem is that we never got real world data, and so the infrastructure was coded, but never tested.  Also, the coding was a lot of copy-and-paste, which is difficult to maintain.  I am very sorry.  It is always an open question how much of badly tested/badly maintained material we should have in the contribs, but in fact our main focus is to maintain core matsim, and contribs are done when we have time or when we have projects that use them.  Please keep us posted if you can solve it.  Sorry again, best wishes, Kai
