### ISSUE TITLE
Can freight scenarios be scaled down?

### ISSUE THREAD

**Issue by cllorca1** [matsim-org/matsim-code-examples#162]
Dear all, 

I am using the freight contribution of MATSim and wanted to know if somebody has scaled down the population (Carriers or carrier services), and how the different parameters could be scaled: freight vehicle capacity, number of services, service duration, fleet size etc. And how this can be later re-scaled to analyzed outputs. 

Thanks,

**Comment by kt86** [comment]
Dear cllorca1,

the computational time for solving the vehicle routing problems (VRP) of a carrier increases more than linear with the number of services or shipments per carrier. Every carrier will be processed independently from the other carriers. So we usually try to split the whole problem to several (smaller) carriers and / or calculating in the first steps only a more or less representative part/area. 

We also reduce the number of services by combining service at the same link. Depending on your problem definition this can be a very powerful improvement. But you should watch, that the size of your combined service is not too big and can still be loaded from your vehicle(s). 

I can not see, who reducing the service time would help to improve the performance, because the number of services remain the same. The same argument should be valid for reducing the vehicle capacity (combined with the demand of all services).

Best regards,
Kai

**Comment by tschlenther** [comment]
Hi,

if your question is about limiting computation time of tour planning in JSprit, Kai provided everything to know. However, if you want to speed up the simulation with MATSim, you might actually think about scaling down the number of tours. In that case, you should be aware that if you cut out services (and do not combine them, as Kai suggested) this has a direct effect on the tour planning. For instance, distances between services in a tour start to grow. So you would rather run JSprit with 100% of the (combined) services and then sample the tours, than sampling the services. However, this does not cut down JSprit's computation time..

Best regards,
Tilmann

**Comment by JWJoubert** [comment]
Hi @cllorca1 why do you want to scale down? Both @kt86 and @tschlenther's arguments are sound. Scaling down freight can have all sorts of unintended consequences. If you want to scale down because you also model (concurrently) passengers (private cars and/or public transport), then there are other ways to _simplify_ the model.
