### ISSUE TITLE
Next MATSim Tutorial event?

### ISSUE THREAD

**Issue by gaegit** [matsim-org/matsim-code-examples#17]
Good day.

On the [MATSim Events page](https://matsim.org/conferences/), there is no scheduled event in the near future. I was wondering if there are any planned tutorial events in 2018, similar to the ones held in 2016 [@Davis USA](https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/68091909/MATSim+Tutorial+Davis+CA+USA+2016) and [@Tongji China](https://matsim.atlassian.net/wiki/spaces/MATPUB/pages/58130436/MATSim+Tutorial+Tongji+University+Shanghai+China)?

I asked [this question in march 2018 in the old Confluence Q&A site](https://github.com/matsim-org/matsim-code-examples/wiki/faq-195952676), but got no answers. Hoping for more feedback this time.

Regards,
Gretar

**Comment by jfbischoff** [comment]
Hi Gretar,

there is no masterplan regarding when and where Tutorials are planned. Usually, these tend to happen on request of someone (such as in Davis) and we then make these open to the public and others could join. 

Since these tutorials tend to happen without too much commercial interest, organizing them is often rather a slow procedure.

Cheers,
Joschka

**Comment by gaegit** [comment]
Thank you for your reply.

**Comment by Mayoookh** [comment]
Hello, 

It would be great if you consider a tutorial in upcoming time. Probably, more people would be interested to join too in 2019. 

Thank you.
