### ISSUE TITLE
Implementing distance based fare for drt/av/taxi and pt modes

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#188]
Hello everyone,
I am working on a scenario which implements distance based fare for taxi/drt/av and pt. I tried to implement it using the 'monetaryDistanceRate' in the mode parameter setting of the modes. However, results indicate that this term is not at all used in the scoring function as the modal share is not sensitive to the values specified for 'monetaryDistanceRate' in the config file. I tried this with versions 10, and also snapshot of 12, but the results are the same. 
If not  'monetaryDistanceRate', is there any other way I could implement the fare for these services?
@jfbischoff  @michalmac

**Comment by ikaddoura** [comment]
Just use the fare module, see here: https://github.com/matsim-org/matsim/tree/master/contribs/av/src/main/java/org/matsim/contrib/av/robotaxi/fares/drt and use the fare config group parameters (e.g. distance based fare).

**Comment by ghost** [comment]
Hello Ihab,
 Thanks for the reply. 
Is the 'fares' module different from the 'scoring' module in robotaxi in version 10? The 'scoring' module in robotaxi (version 10) also has a fare handler. I tried this and it does not have an impact on the modal share either.

**Comment by jfbischoff** [comment]
Fares should be used as the the exact distance of a taxi or DRT trip is not known before the trip is made and thus the distance in the plan is not very accurate (or in case of taxi, not even provided).  

It's maybe not ideal, but then again taxi fares are often more complicated than what the standard mode scoring can offer.

`Is the 'fares' module different from the 'scoring' module in robotaxi in version 10? The 'scoring' module in robotaxi (version 10) also has a fare handler. I tried this and it does not have an impact on the modal share either.`

These are the same, they were just renamed from scoring to fare, because that depicts the name a little bit better.

**Comment by ghost** [comment]
Thanks Joschka!
