### ISSUE TITLE
NetworkChangeEvents and error while compiling

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#223]
Does MATSim support more than one networkChangeEvents.xml file? In my simulation, in a disaster case study, network changes happen at different times, so I had created different 
networkChangeEvents.xml files. However, every time I was going to do the simulation it gave an error. After that, I merged these files into one, but I can't do the simulation. Does anyone know why this?

File with the networkChangeEvents.xml and the logfile.log - [networkLog.zip](https://github.com/matsim-org/matsim-code-examples/files/3772825/networkLog.zip)

Thank you in advance!

**Comment by kainagel** [comment]
No, not multiple files.  But the way you have merged into one file looks ok and should work.  What is the error message?  (The logfile does not contain one ... or does it just hang?) . And: Could you please try running it with very small (instead of exactly zero) values for capacity and speed and see what you get?

**Comment by OrranaLhaynher** [comment]
The simulation crashes completely. In one of the tests, I left it for 2 hours and the simulation just didn't end. And I don't know why.

**Comment by OrranaLhaynher** [comment]
After changing the flowCapacity and freeSpeed values the simulation finally worked. Thank you very much!

**Comment by kainagel** [comment]
Given that using small values instead of zero worked, the attempt of an explanation: From the logfile, it looked like the simulation got hung up in PersonPrepareForSim.  This often means that the router gets stuck somewhere.  And one can imagine that if a connection from A to B can't find another path except one over a link with speed zero, then it never arrives.  (This does not explain why the router does not simply crash, but hm.)
