### ISSUE TITLE
Non-global road decongestion

### ISSUE THREAD

**Issue by OrranaLhaynher** [matsim-org/matsim-code-examples#229]
Hello! At the end of the simulations made for my scenario, I noticed that there was congestion on some roads. Because the scenario is an evacuation, these jams are negatively influencing the evacuation time of agents. So I've been looking for ways to minimize these congestion by rerouting agents when they are in this situation, since I didn't want to do global decongestion. But I didn't find any code that could be used as a guide for that. Does anyone know if agent rerouting is possible in a congestion situation in MATSim? And if so, are there any codes I can rely on?

Thank you in advance!

**Comment by kainagel** [comment]
In general, there is the "decongestion" contrib.  Could you please describe how you are using matsim (preferably as clone of matsim-example-project; which version; ...) so I can think about an easy way to explain that?

Also, I should point out that the decongestion contrib pushes the system from Nash Equilibrium towards System Optimum.  I.e. you get evacation paths that are "faster", but that are not stable if evacuees make decisions for themselves. So politically you would need to think about enforcement.  (I have indeed an evacuation project where we are using this, and they are assuming that they will put up road blocks.)

**Comment by OrranaLhaynher** [comment]
The version of MATSim in the pom.xml is 11.0 and I have clone the simulator repository for use. And I'd love to if you could explain me more about it. Thank you!

**Comment by kainagel** [comment]
And how are you running it?

(And, as a side note: Please think about cloning "matsim-example-project" instead of "matsim".  I will eventually stop supporting people/teams who clone matsim as a whole without a reason.)

**Comment by OrranaLhaynher** [comment]
I didn't clone the MATSim repository but the matsim-example-project repository. And then I imported it as a Maven project, as exemplified in the official website installation tutorial. The IDE I am using is VS Code and all the code made for the simulations is compiled by it.

**Comment by OrranaLhaynher** [comment]
Hello again! I tried to run DescongestionRunExample, but couldn't because it was giving error while importing the classes used in the script. Do you know if there are any errors with the package?

The repository of my project -> https://github.com/OrranaLhaynher/matsim-example-project

Thank you in advance!

**Comment by kainagel** [comment]
Mostly the maven dependency is missing in your pom.xml (contribs need to be explicitly added as dependencies; see the pom.xml in https://github.com/matsim-org/matsim-code-examples for examples):
```
<dependency>
<groupId>org.matsim.contrib</groupId>
<artifactId>decongestion</artifactId>
<version>${matsim.version}</version>
</dependency>
```
Does this help?  If not, could you please give me write access to your repo then I could push it back.

**Comment by OrranaLhaynher** [comment]
Yes, that helped a lot. Thank you! I finally managed to run the example. Thanks a lot!

Sorry to bother you, but you had said that the paths generated with the decongestion contribution are not stable. And that with that I would have to think about enforcement. Could you explain me more about this?

**Comment by ikaddoura** [comment]
The decongestion contrib coputes monetary correction terms (per link and time bin) to change individual travel decisions towards and push from Nash equilibrium to the system optimum. The monetary correction terms could be interpreted as a dynamic toll or any other policy with a similar effect.
Once the decongestion contrib is disabled and the monetary correction terms disappear, transport users have no longer any incentive to behave optimal and will fall back to their "normal" behavior. In consequence, the travel behavior moves back from the system optimum to Nash equilibrium... This may for example happen if you use the output_plans from a decongestion simulation run and then start a new default simulation run (without the decongestion contrib).

**Comment by OrranaLhaynher** [comment]
First, thank you very much for your reply! It clarified some of my doubts. But some still persist, especially one: would this monetary correction be some kind of enforcement (as explained by the kainagel) or not?

**Comment by kainagel** [comment]
Trying to clarify: The decongestion contrib pretends to charge a toll on congested segments.  In consequence, they become less attractive, and the "best path algorithm" starts finding other routes.  Since MATSim is stochastic, also the result will be stochastic, i.e. fluctuate from one iteration to the next.  To translate this into policy, you would need to make some decision there (e.g. average over several iterations, or use the routes of the last iteration; in either case, you will not get "the best" solution, but still a "good" one).

Re "enforcement": What I mean was that once you know the "designated" routes, and you know that they are not Nash-stable (i.e. evacuees would unilaterally benefit from switching to faster routes, while at the same time degrading overall system performance), you will have to do something to make sure that evacuees stick to the "designated" routes if you want to use them in the real world.  As stated, in one case where we do work, it is envisaged to put up road blocks at those places where evacuees could switch from the designated routes to other ones.

Clearly, quite overall one needs to be really careful with evacuation recommendations.  If this is not only a purely scientific exercise, you need to be in close contact with practitioners.  Also, you need to present your "designated" routes to the practitioners, ask them if they make sense to them, and if not why not, and then adapt the simulation to their concerns.  Ultimately, hopefully all of you together can come up with a bundle of routes that make sense and are plausible.  Then, they should again be verified in some way ... on the matsim side, by running them again through a pure mobsim without iterations.  And preferentially also by some other tool, or at least through the practitioners' intuition.  And still, in the end, the best we can do is say that "if everything goes according to the assumptions of the simulation, then X, Y, and Z will happen".   If you need more certified results, these people https://www.traffgo-ht.com/en/ may be helpful; they have more experience than we do in how to align stochastic simulation and certification.

**Comment by OrranaLhaynher** [comment]
Thank you! Your answer finally clarified all my doubts.
