### ISSUE TITLE
Expert opinion about the feasibility of my master`s issue

### ISSUE THREAD

**Issue by Alnik89** [matsim-org/matsim-code-examples#251]
Now that I have read through some passages of the book during the weekend I can tell that I have a rough understanding about the functionality of MATsim.
At this point I would like to ask for the opinion of some experts to save time and prevent frustration.
Specifically, my issue refers to a part of my upcoming master`s thesis, which I would like to work on with MATsim.
To describe the goal.
As part of my master's thesis, I would like to rate mobility concepts with regard to their effectiveness in relation to the infrastructure of a model region (small) of a rural area.
For this purpose, I would like to make a concrete statement about the availability (waiting time), accessibility (limited to groups of people?) and the degree of fulfillment of the distance (door to door ability) of private transport, public transport (ÖPNV) and public transport (demand-driven bus).
My limited or non-existent experience with MATsim makes it difficult for me to assess my intentions in terms of feasibility and effort.
Therefore my question to the experts:
Is my concern generally portrayed with MATsim?
And
Is the effort to create a model in MATsim for a layman ("programming experience" only Matlab and Simulink) in the context of a master's thesis (4-6 months) doable?

**Thank you very much for any answer**

**Comment by tschlenther** [comment]
> Is my concern generally portrayed with MATsim?

Yes it is!

> Is the effort to create a model in MATsim for a layman ("programming experience" only Matlab and Simulink) in the context of a master's thesis (4-6 months) doable?

This is really hard to say. What data basis do you have? Do you maybe have a demand already?
How large is the scenario/area? How many and which transport modes do you plan to model?

I, personally, do not have experience with _building_ a model. So this is why i find it hard to say yes or no here. You would definitely have to do some programming in Java, so it also depends on how you feel about that.

Maybe @Janekdererste or @ikaddoura can say a little bit about this, too?

**Comment by Janekdererste** [comment]
I guess the answer is: It depends. Building a good model is quite difficult. If only commuters are sufficient for you. You could go ahead and create some home -> work -> home plans with statistics from the Argentur für Arbeit (Assuming, you're from Germandy, since you used the term ÖPNV). There is an example on how to do this [here](https://github.com/matsim-org/matsim-code-examples/tree/11.x/src/main/java/org/matsim/codeexamples/population/demandGenerationFromShapefile)

If you want to have a more realistic demand I'd say, this is out of scope for a master's thesis, since conducting the study you proposed will be challenging already if you are not experienced with the software.
