### ISSUE TITLE
Error in running matsim from GUI

### ISSUE THREAD

**Issue by prvnpandey** [matsim-org/matsim-code-examples#261]
Error in custom provider, java.lang.IllegalArgumentException: There exists already a node with id = 1000793615.
Existing node: [id=1000793615][coord=[x=1429162.60462202][y=4972830.591528221]][type=null][nof_inlinks=1][nof_outlinks=1]
Node to be added: [id=1000793615][coord=[x=1429162.60462202][y=4972830.591528221]][type=null][nof_inlinks=0][nof_outlinks=0].

I have checked network file but this above node id is defined at once only, please look into it I am also attaching all 3 files for checking.

[MATSIM_SIMULATION.zip](https://github.com/matsim-org/matsim-code-examples/files/4007621/MATSIM_SIMULATION.zip)

**Comment by kainagel** [comment]
Hello, not sure if that still is an issue.  The network file looks ok.  I would speculate that you are, directly or indirectly, reading the network file twice.  This speculation is corroborated by the fact that the coordinates of the "existing node" and the "node to be added" are exactly the same.  The different number of inlinks/outlinks is not a counter-argument, since those are added later.
