### ISSUE TITLE
Why RandomizingTimeDistanceTravelDisutility only randomizes Distances but not Travel times?

### ISSUE THREAD

**Issue by davibicudo** [matsim-org/matsim-code-examples#270]
Hi, 

in the [RandomizingTimeDistanceTravelDisutility](https://github.com/matsim-org/matsim/blob/master/matsim/src/main/java/org/matsim/core/router/costcalculators/RandomizingTimeDistanceTravelDisutility.java) only the travel distances are randomized. Is there a reason for not randomizing the whole cost? In some cases one might set the marginalCostOfDistance to 0 and route only with travel time, thus losing the randomization.
Also, could someone please explain (or link to an explanation) of why the randomization is applied?

![image](https://user-images.githubusercontent.com/28100741/72432524-8e95e900-3797-11ea-9dec-5252b7dda805.png)

Thanks!

**Comment by JWJoubert** [comment]
Hi @davibicudo I am going to try and explain - others may chip in. It also took me some time figuring it out, but it is actually, in my view, a pretty neat bit of functionality. Firstly, both time and distance are randomized (your code snippet relates to time).

The `logNormalRmd` is just _wiggling_ the `marginalCostOfDistance` a little bit. In essence, then, the person's (actually, the routing algorithm's) _experience_ of the link's travel time is slightly altered from the link deterministic (free speed) travel time. When adding up the links' travel times on a route, the experienced travel time is (pseudorandomly) different from the deterministic route time calculated without the _wiggling_.

**Comment by JWJoubert** [comment]
As a result of the _wiggling_ of the _experienced_ distance, the calculated _shortest_ route may be a different one from the deterministic shortest route. But only slightly. 

So this mechanism allows you to randomise the route you get. This is actually much simpler, I argue, than trying to come up with a route that is _just slightly_ different from the current one. If it turns out that this random route performs better than previous routes taken, it is likely to survive the co-evolutionary machinery and remain among the memory of plans.

**Comment by kainagel** [comment]
Here is also some material to read:
 * <a href="https://arxiv.org/abs/1002.4330v1">https://arxiv.org/abs/1002.4330v1</a> for how to generate route alternatives (where Pareto routing is one option)
 * <a href="https://doi.org/10.1016/j.procs.2014.05.488">https://doi.org/10.1016/j.procs.2014.05.488</a> for a paper testing the approach.

**Comment by mrieser** [comment]
But currently the randomization only works if `marginalUtilityOfDistance` is used (i.e. `!= 0`). In scenarios where `marginalUtilityOfDistance = 0`, the randomization will never have an effect, as `logNormalRnd * this.marginalCostOfDistance` will always result in 0.

- Why isn't the whole cost randomized, i.e. `return logNormalRnd * (this.marginalCostOfTime * travelTime + this.marginalCostOfDistance * link.getLength());`?
- If it is by design only applied to the distance, a warning in the constructor in the case of `marginalUtilityOfDistance == 0` would be helpful, stating that the randomization will have no effect.

**Comment by kainagel** [comment]
There are certainly multiple ways in which one could apply randomness to routing. This here does _not_ do Link cost randomization, since that is known to not work well in large networks (see the above arxiv.org reference).  Instead, it draws the tradeoff between two criteria randomly, and then keeps that fixed for each routing call.  If one does single criterion routing, then evidently it has no effect.

The config comment is actually better: "strength of the randomness for the utility of money in routing under toll.  Leads to Pareto-optimal route with randomly drawn money-vs-other-attributes tradeoff."  

Unfortunately, the whole way in which this is plugged together is buggy; e.g. it does not honour the config value except in the context of road pricing.  I think it was just moved from the roadpricing contrib to the main matsim repo at some point, without thinking about the ramifications.  Which means cleaning it up is not something I can do between two other tasks.   However, using it as a building block in a java-scripted matsim setup should be possible, and it should to Pareto routing.

**Comment by davibicudo** [comment]
Thanks a lot for the clarifying answers and for pointing additional resources! Now it is clear why randomization is applied to only one part of the cost and makes quite sense.
I'll close the ticket now but will refer to it in the future when the topic becomes an issue here once again.
Best!
