### ISSUE TITLE
Config file for "carrierPlansWithoutRoutes.xml"

### ISSUE THREAD

**Issue by giftchega** [matsim-org/matsim-code-examples#276]
Hi team,

I am trying to simulate freight transport for "carrierPlansWithoutRoutes". Can someone please assist with the config file. 

[carrierPlansWithoutRoutes.zip](https://github.com/matsim-org/matsim-code-examples/files/4110008/carrierPlansWithoutRoutes.zip)

**Comment by kt86** [comment]
Hello giftchega,

setting the freight related content in the config file is a relatively new development (fall 2019). 
You can find some hints how to set the config parameters in code, here:  
https://github.com/matsim-org/matsim/blob/5cf27bc1b7882e8ccc3159b8d0d79dab2ceb0e3f/contribs/freight/src/main/java/org/matsim/contrib/freight/usecases/chessboard/RunChessboard.java#L140-L151

I am still working on some more supporting features in the FreightUtils class and will update the example provided in the code-examples-repository (https://github.com/matsim-org/matsim-code-examples/blob/12.x/src/main/java/org/matsim/codeexamples/extensions/freight/RunFreightExample.java) afterwards.

-- 
Beside of that, please make sure that the specified doctype of your .xml - file fits to its content. In your example you specify that the reader/parser should find a network (v1) and not a carriers file.
<img width="571" alt="grafik" src="https://user-images.githubusercontent.com/12124568/73174086-2c2dd880-4107-11ea-8a41-daf609c9c968.png">

You can replace lines 3-4 by 
```
<carriers xmlns="http://www.matsim.org/files/dtd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	  xsi:schemaLocation="http://www.matsim.org/files/dtd http://www.matsim.org/files/dtd/carriersDefinitions_v2.0.xsd">
```
to use the current validation format. 
(Since there was no validation for the carriers file in previous versions, it also should work without any validation information -> remove only line 3. In this case you may get some warnings errors.)

**Comment by kt86** [comment]
The RunFreightExample has been updated. -> branch 13.x. Closing this Issue here.
