### ISSUE TITLE
Error while running drt contrib (SNAPSHOT 12)

### ISSUE THREAD

**Issue by ghost** [matsim-org/matsim-code-examples#282]
Hello,

  I am running a scenario with the drt V12 SNAPSHOT and I get the following error.

'java.lang.IllegalArgumentException: acttype "drt_B interaction" is not known in utility parameters (module name="planCalcScore" in the config file).'

Is it necessary to define such an activity in the config file (I suppose this is similar to the 'pt interaction' activity which we need not mention in the input config file)? 
If so what should be its duration?
Any help would be deeply appreciated.
@jfbischoff @michalmac 

Regards,
Jishnu

**Comment by michalmac** [comment]
Yes, it needs to be specified. There are some default for "pt", "drt" etc... but if you want to use non-standard names of modes, such as "pt2" or "drt_B", you need to add the corresponding parameters manually to the config.

This is how it is specified in one of the examples:
https://github.com/matsim-org/matsim/blob/1c37eee480e459262b34e1a72cb5f6c7f632b5da/examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml#L72-L73

**Comment by kainagel** [comment]
Sounds like something we could now repair with our newer infrastructure, and we should actually do so.

@component: gleich

Yes, it needs to be specified. There are some default for "pt", "drt" etc... but if you want to use non-standard names of modes, such as "pt2" or "drt_B", you need to add the corresponding parameters manually to the config.

This is how it is specified in one of the examples:
https://github.com/matsim-org/matsim/blob/1c37eee480e459262b34e1a72cb5f6c7f632b5da/examples/scenarios/dvrp-grid/multi_mode_one_shared_taxi_config.xml#L72-L73<http://quarantine.tu-berlin.de:32224/?dmVyPTEuMDAxJiY1ZTVjNjc5N2Y5ZjNhZDFlMD01RTNDN0FENV83NTk0Nl83MTc4XzEmJmEyZjgzY2Q4MmQ2NGI0MD0xMjMyJiZ1cmw9aHR0cHMlM0ElMkYlMkZnaXRodWIlMkVjb20lMkZtYXRzaW0tb3JnJTJGbWF0c2ltJTJGYmxvYiUyRjFjMzdlZWU0ODBlNDU5MjYyYjM0ZTFhNzJjYjVmNmM3ZjYzMmI1ZGElMkZleGFtcGxlcyUyRnNjZW5hcmlvcyUyRmR2cnAtZ3JpZCUyRm11bHRpJTVGbW9kZSU1Rm9uZSU1RnNoYXJlZCU1RnRheGklNUZjb25maWclMkV4bWwlMjNMNzItTDcz>

**Comment by vsp-gleich** [comment]
Actually these stage activity types should already be added automatically here: 
[https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L47-L49](https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L47-L49)

If I see it right, there might be an issue with using subpopulations (it checks only for the default population if the activity type is existent, but adds for all subpopulations).

@Jishnuns If you send me your config file I can try to look into this.

**Comment by ghost** [comment]
Thanks for the reply. I have atached my config file (I have also added the drt_B intercation as an activity in the config
[config.txt](https://github.com/matsim-org/matsim-code-examples/files/4170658/config.txt)

).

**Comment by vsp-gleich** [comment]
Ok, I think the situation is the following:
[https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L47-L49](https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L47-L49) adds the stage activity always for the two stop based operation schemes `stopbased` and `serviceAreaBased`, which is right.
However, the default operational scheme is `door2door` that used not to have access and egress walk legs. So if `plansCalcRouteCfg.isInsertingAccessEgressWalk() == false` (the default), `DrtConfigs` does **not** add the stage activity, because passengers are beamed to the road network just like for car trips. 
This is something that creates lots of modelling problems so we want to phase it out and mostly use the config switch config.plansCalcRoute().setInsertingAccessEgressWalk( true ); (can only be set in code, not in the config file).
DrtConfigs checks for this and adds the stage activity if operational scheme is `door2door` _and_ `plansCalcRouteCfg.isInsertingAccessEgressWalk() == true`.
In the mean time DrtRoutingModule was restructured and replaced several times and now always returns access and egress walks, no matter what is set in plansCalcRouteCfg.isInsertingAccessEgressWalk().

We can now either add the stage activity in `DrtConfigs` always, in all circumstances or we can rebuilt the routing again to _not_ add access/egress walk legs if `plansCalcRouteCfg.isInsertingAccessEgressWalk() == false`. I would prefer the former. Ok?

**Comment by michalmac** [comment]
Right now `DvrpRoutingModule` ignores `plansCalcRouteCfg.isInsertingAccessEgressWalk()`, because access or egress can be of any mode, not only "walk". The default is to insert walk. Here is some info on how to modify access/egress modes: https://github.com/matsim-org/matsim/pull/727

@vsp-gleich Maybe we should remove this condition? https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L45

**Comment by vsp-gleich** [comment]
I think it should be now a rare case to use `door2door` drt with `plansCalcRouteCfg.isInsertingAccessEgressWalk()` and it's ok to have the activity param for the (unused) stage activity type set up anyway. 
I will remove the whole if block, because we currently have no situation in which we shouldn't add the stage activity type. [https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L42-L45](https://github.com/matsim-org/matsim/blob/666047ec491f30eca0eb9d691c036279d798f72c/contribs/drt/src/main/java/org/matsim/contrib/drt/run/DrtConfigs.java#L42-L45)

**Comment by vsp-gleich** [comment]
See pull request: [https://github.com/matsim-org/matsim/pull/812](https://github.com/matsim-org/matsim/pull/812)
