### ISSUE TITLE
Real-time simulation

### ISSUE THREAD

**Issue by amrlafi** [matsim-org/matsim-code-examples#309]
Is it possible in MATSim to run simulation in real-time? In other words if the simulation is starting at 8 AM, it should take 3 hours to reach 11 AM, during this period events will trigger throughout the simulation. A good example is Via visualizer, the user can run a simulation in real-time.

**Comment by kainagel** [comment]
There is a `PlayPauseSimulationControl` interface which, if you know multithreading, is able to put the mobim on one thread and have it controlled from some other thread.  There, you have commands such as `doStep(time)` which means that you can progress until time.  I.e. you could have an external (say second by second) clock, and then run matsim also second-by-second.

Having said that, I have to say that I am not totally sure what to do with this.  Even if one is running matsim in real time settings for traffic control, the goal would normally be to run much faster than real time so that, say, many control strategies can be tried out.

**Comment by amrlafi** [comment]
Thanks for your reply @kainagel. In my case I'm calling a web service on **LinkEnterEvent** and **LinkLeaveEvent**. Running the simulation at once is not realistic in my case. Via (the simulation runner) allows the user to run the simulation in real-time, so for sure it's doable :)

**Comment by mrieser** [comment]
Please not that Via is **not** running the simulation, it is only visualizing the simulation output. And this visualization can happen at different speeds or even backwards in time, which clearly is not possible with the actual simulation.
