### ISSUE TITLE
Total Distance and Time Driven

### ISSUE THREAD

**Issue by vasilis-mourtakos** [matsim-org/matsim-code-examples#310]
Hello MATSim community, 
I've written an algorithm that attempts to **calculate the total distance and time driven per vehicle for every 5min using the Output_Events data**.
My issues are, specifically when calculating the distance driven: ( I'm using a 10% scenario, cars and av taxis are simulated, QSim, FIFO for linkDynamics and false for removeStuckVehicles)

A) I'm not quite sure how the "Enters Traffic" and "Leaves Traffic" tags work in terms of where in the link traffic queue are placed. I have conducted some tests and I've seen that when a vehicle "Enters Traffic", it leaves in the exact next time step or in some cases a little later but in all my tests none other vehicle left sooner than one that had just entered. About "Leaves Traffic" I think that it just takes the vehicle out of the queue when it reaches the destination, despite its position in the queue.

B) I don't know how to deal with the exceeding of the storage capacity of the links. In my simulation, many links' storage capacity is exceeded. I understand it's due to the removeStuckVehicles being false, but I need to take it into consideration. I mean when the vehicles are in a queue that exceeds the storage capacity of a link, they are not actually traveling any distance (because that would lead to major increase in distance driven), but are still active in the network . 

The two issues are connected because when I try to combat B) with some logic of calculating distance by monitoring moving traffic and not letting vehicles travel more distance in a link than the available length*lanes, I come across some weird results because of A). 

Any suggestions/thoughts? 

Thank you for your time, 
Vasilis Mourtakos

**Comment by mrieser** [comment]
Regarding A) All vehicle-interactions take place at the end (near the to-node) of a link. So your observation is correct, that (in most cases) a vehicle entering traffic leaves that link in the next time step. For leaving traffic, the vehicle can leave the link once it is in the front of the queue and would be the next vehicle to move to the next link (which this vehicle doesn't have).

Regarding B) "many links' storage capacity is exceeded". Is this based on a custom analysis of yours, or based on the warnings presented in the logfile somewhere near the start? Especially on short links with high flow capacity, the storage capacity is automatically increased in order for the flow-capacity to be reachable. 

Usually in MATSim, to calculate travelled distances, we just sum up the lengths of the travelled links, counting the destination and but ignoring the start link (because, as you figured out, the interaction happens in MATSim at the end of the link).

I don't understand the part of `length * lanes` for a single vehicle: A vehicle only passes a link once, on one lane, but not multiple times on each lane. So the distance of a single vehicle on a link should always be the link's length.

**Comment by vasilis-mourtakos** [comment]
> Regarding B) "many links' storage capacity is exceeded". Is this based on a custom analysis of yours, or based on the warnings presented in the logfile somewhere near the start?

It's from custom analysis, where I compared the storageCapacity of a link (10% * length*lanes/7.5) to the vehicles that are currently in the link. Links' capacities are exceeded some times more than 100+% but I'm ok with it because I'm actually trying to test the resilience of the system to "extreme" situations. 
> Especially on short links with high flow capacity, the storage capacity is automatically increased in order for the flow-capacity to be reachable.

Just to clarify this part. Let a link have a calculated storageCapacity of 0.5 vehicles ( 10% * length*lanes/7.5). If the flowCapacity is 1200 vehicles/hour or 20 vehicles/minute, for the 10% scenario it would be 2 veh/minute. Will the storageCapacity increase to 1 or 2 vehicles?
> Usually in MATSim, to calculate travelled distances, we just sum up the lengths of the travelled links, counting the destination and but ignoring the start link (because, as you figured out, the interaction happens in MATSim at the end of the link).

I did that at first, but I wanted to bring more detail to my research and account for the distance that vehicles waiting in queue are traveling. Like when you are in a big line of traffic in real life and you are moving for some distance at a time until you leave that specific road (link). I will give it another try or I will calculate the distance as you mentioned. 

> I don't understand the part of length * lanes for a single vehicle: A vehicle only passes a link once, on one lane, but not multiple times on each lane. So the distance of a single vehicle on a link should always be the link's length.

You are right, I got confused with the capacity. 

Thank you very much for your time and thoughts!
