### ISSUE TITLE
DRT: large computational time

### ISSUE THREAD

**Issue by ChristophTraf** [matsim-org/matsim-code-examples#318]
We are facing the problem that the computational time increases with each iteration. Is there a way to speed up the Qsim?

Could this problem be related to the available memory?
The MATSim MemoryObserver shows for example 30910 free MB from in total 70358 MB. Our MATSim computer has 128 GB memory available. I assume that this memory display refers to the memory of the Java virtual machine?!

Please see attached the stopwatch and the log file:
![stopwatch](https://user-images.githubusercontent.com/45175469/78866902-8a990080-7a40-11ea-93b0-83a99f49b7b7.png)

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/4454541/logfile.log)

**Comment by ikaddoura** [comment]
Your logfile tells me that in each iteration the number of DRT legs increases. For a larger number of drt legs, also the computation time of the mobsim increases (more trips requests to handle and so on).

We were facing a similar problem and then used this module to speed everything up: https://github.com/matsim-vsp/drt-speed-up
(The idea is to not simulate the DRT mode in every iteration.)

See this run class for an example how to use the drt-speed-up: https://github.com/matsim-scenarios/matsim-berlin/blob/5.5.x/src/main/java/org/matsim/run/drt/RunDrtOpenBerlinScenarioWithDrtSpeedUp.java

... and see this paper for some more information about the speed-up:
https://depositonce.tu-berlin.de/handle/11303/10831

**Comment by ChristophTraf** [comment]
Thank you very much for your response and the link to your paper! Yesterday we came across this drt-speed-up-tool.
I think I will try it and compare the results to the standard approach.

**Comment by ChristophTraf** [comment]
With the SpeedUp module the computing time is now significantly reduced.

![stopwatch](https://user-images.githubusercontent.com/45175469/79205018-b3a10300-7e3d-11ea-8cb1-5764cec5abc7.png)


What is not quite clear to me yet is the scoring. In each iteration, in which DRT is explicitly simulated, the score decreases significantly. Is this due to for example to congestion effects which are not recognized by the approximation, or could it be related to the fare module? In our original setup we didn’t use any fare module (I tried do set the parameters to 0).
Thank you very much!

![scorestats](https://user-images.githubusercontent.com/45175469/79205101-cadff080-7e3d-11ea-9b7a-d15da3c5834f.png)

**Comment by vsp-gleich** [comment]
Your score statistics looks weird. We have run simulations with and without drt fares and never observed such drastic score decreases in simulated drt iterations. However, we usually have drt as one of multiple modes. If a smaller share of all trips is done by drt, the effect of drt on the score averaged over the whole population is less pronounced. Still the largest score decreases I found in one of our simulations was very small:
![Z140e scorestats](https://user-images.githubusercontent.com/10728293/79207715-5909a600-7e41-11ea-8b81-8c737924bde0.png)
Worst and executed scores were slightly lower every 10 iterations when drt is simulated (and not teleported) (drt about 6% mode share, no drt fare, (open-berlin run Z140e))

In the teleported simulations drt riders are teleported with a travel time that is estimated based on average drt wait time and average in-veh. beeline speed in the last simulated drt iteration. 
https://github.com/matsim-vsp/drt-speed-up/blob/af2a6a79cfb1a5a77979ef44ae8a3718ee0ec583/src/main/java/org/matsim/drtSpeedUp/DrtSpeedUp.java#L227

It is logical that this turns out too optimistic for some agents, e.g. if many drt trips in the last simulated iteration used a fast and direct motorway (-> high average beeline speed) and later in the teleported iterations an agent switches to drt for a trip on a slow circuitous road around a lake the beeline speed averaged including fast trips on a straight motorway might turn out too optimistic. The agent riding drt around the lake will only notice in the next simulated drt iteration, so a slight decrease in score in the simulated drt iterations seems plausible to me.

For our scenarios in rather flat and not soo heterogeneous areas drt-speed-up worked fine, but I can imagine that in scenarios where average beeline speed is a bad approximation of travel time the current drt-speed-up implementation can create too much noise and might be inappropriate. You could try to route drt riders on the road network in the teleported iterations instead of beeline travel time by creating you own drt-speed-up fork. We did not, because routing on the road network is fast, but beeline is even faster ;-)

**Comment by ChristophTraf** [comment]
Thank you!
Is this “open-berlin run Z140e” a config file? Could you tell me where I can find this config without fare?

Could you also explain to me how I can use the SpeedUp tool without the fare module? Without fare module I get a NullPointException in DrtSpeedUp.java (L133) (https://github.com/matsim-vsp/drt-speed-up/blob/master/src/main/java/org/matsim/drtSpeedUp/DrtSpeedUp.java).

Another thing that I don’t understand is the purpose of the intermodalTripFareCompansators module.

Thank you so much for helping me with this 😊

**Comment by vsp-gleich** [comment]
> Is this “open-berlin run Z140e” a config file? Could you tell me where I can find this config without fare?

This was more internal information in case a colleague is reading this. However a config without drt fare can be emulated by setting all parameters in the drt fare config group to 0 (=deduct 0 fare). Drt-speed-up has to emulate the DrtFareModule, because the latter does not deduct drt fares for teleported pseudo-drt. Currently drt-speed-up is configured in a way that it always needs a drtFare configGroup.

> Another thing that I don’t understand is the purpose of the intermodalTripFareCompansators module.

That is something experimental we are trying around with in matsim-berlin. We will report when it is done. You don't need it to run drt-speed-up. If you don't want to remove it from the run class you can just set compensations to 0 and it will have no effect (besides PersonMoneyEvents with amount 0).

**Comment by ChristophTraf** [comment]
I have tried to calculate the routing distance instead of the beeline distance. In most cases, the routing distance is greater compared to the beeline distance. But the results are quite similar with a slightly higher score each tenth iteration compared to the approximation with the beeline distance.

Now I will set a small fare and see what’s happening.
Unless you have a better suggestion that I could try?! 😊
