### ISSUE TITLE
Launchung OTFVis

### ISSUE THREAD

**Issue by HubbleCommand** [matsim-org/matsim-code-examples#341]
Hello

I've been trying to get OTFVis to launch, but I can't seem to get it working.  I've tried a few different commands, variants of :
`java -Xmx500m -cp path\to\org\matsim\matsim\11.0\matsim-11.0.jar: path\to\org\matsim\contrib\otfvis\11.0\otfvis-11.0.jar org.matsim.contrib.otfvis.OTFVis`

But I either get :
`Error: Could not find or load main class path\to\org\matsim\contrib\otfvis\11.0\otfvis-11.0.jar (This file does exist though).`

Or a JNI error: 
`Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: org/matsim/vis/snapshotwriters/VisMobsim
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.matsim.vis.snapshotwriters.VisMobsim
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more`

However, I read somewhere that OTFVis was supposedly stopped (https://github.com/matsim-org/matsim-libs/blob/master/matsim/docs/user-guide/chapters/visualization.tex), so I don't know if there's a point in trying to get it to work?

**Comment by jalal1** [comment]
I guess you are missing the needed libraries. I am using OTFVis and below in yellow what you need : 

![image](https://user-images.githubusercontent.com/1554493/82720682-6a817180-9c7b-11ea-9f64-10dd52493367.png)

This is the command inside run.sh : 
java -Xmx5000m -cp otfvis-0.11.0-SNAPSHOT.jar org.matsim.contrib.otfvis.OTFVis

**Comment by HubbleCommand** [comment]
Yep, I don't have the libs folder. How did you install OTFVis? I just used the OTFVis provided by the MATSim Maven project.

**Comment by jalal1** [comment]
In fact, I didn't dig deeper to understand which .jar files inside 'libs' that makes it work. What I can suggest is to try the same 'libs' folder you have with MATSim, as I supposed you have MATSim running fine. 

If you find the exact needed .jar files, you can update this thread to help other people :)

**Comment by HubbleCommand** [comment]
I tried copying over the OTFVis jar from the maven project into a standalone version of MATSim, but I get the exact same errors. How did you set up your environment?

**Comment by jalal1** [comment]
For some reason, both links are not working:
-  OTFVis under [MATSim extensions](https://matsim.org/docs/extensions/otfvis) or 
- [Build page](https://www.matsim.org/files/builds/)

@kainagel, Where can one download OTFVis ? or can I upload the files I have here? Thank you

**Comment by mrieser** [comment]
It looks like you are using Windows. In this case, use `;` instead of `:` to separate the jar files in your command:

    java -Xmx500m -cp path\to\org\matsim\matsim\11.0\matsim-11.0.jar;path\to\org\matsim\contrib\otfvis\11.0\otfvis-11.0.jar org.matsim.contrib.otfvis.OTFVis

Based on your error message, it tried to interpret the location of the jar-file as the class to start, which is wrong:
```
Error: Could not find or load main class path\to\org\matsim\contrib\otfvis\11.0\otfvis-11.0.jar (This file does exist though).
```
The main class should be `org.matsim.contrib.otfvis.OTFVis`.

**Comment by HubbleCommand** [comment]
Thanks for your help! Although I still keep getting the same error. 

I just realized that I was following the launch method detailed in the 2016 MATSim manual, while I had setup MATSim through importing matsim-example-project as a Maven project. Could that be causing the problems? (although the links to download the nightly build as detailed in the manual no longer work, and I can't find a more up-to-date version of it)

**Comment by kainagel** [comment]
Hm.  In general, OTFVis is no longer supported; it is too messy with its dependencies on certain hardware and software setups.  We recommend using VIA (https://simunto.com/via/), which admittedly is commercial, but through that commercial funding stream is able to generate the resources to support those different hardware and software setups.  It is free up to a certain number of agents, and you can negotiate academic or teaching licenses.

Having said that, the example project actually has all the settings to run otfvis.  See https://github.com/matsim-org/matsim-example-project/blob/master/src/main/java/org/matsim/project/RunMatsim.java .  It should pull in the necessary libraries via maven, and then work from there.  This is, however, the version of otfvis that is plugged into the live simulation.  We haven't used the version that plays back so-called `*.mvi` files for many years now, and maybe we should be honest and remove that functionality.  Given matsim's output, it is not so difficult to re-run the final iteration and to attach otfvis to that, and that is what we regularly do.

In that example project, you should be able to switch between matsim versions by changing the version number in the `pom.xml` file.  

I would somewhat strongly advise against using nightly builds.  We had left that functionality in place since it was there and worked, but the strongly recommended path is to use maven.

This one here: https://github.com/matsim-vsp/matsim-equil may (or may not) run otfvis out of the box.  Maybe it is worth downloading it (the zipfile is enough) and check if otfvis pops up.  The approach is essentially the same as in the example project, except that it has some additional wirings.

**Comment by HubbleCommand** [comment]
OTFVis launches by default when I followed the [Simunto tutorial](https://simunto.com/matsim/tutorials/eifer2019/)  on how to get the example project working in IntelliJ.

I must have done something wrong when I did it with Eclipse.
