### ISSUE TITLE
Potential Reason for "Qsim Simulation AT 94:00:00, 95:00:00, 96:00:00"

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#387]
Hello everyone,

The information screen of my simulation showed as below when running my MATSim scenario
![image](https://user-images.githubusercontent.com/63421908/87061159-b24c6000-c20b-11ea-9c3b-e2c1d1beaebe.png)

As you can see, the information there says agents are running on the QSim even at 94:00:00 am (possibly?). Since MATSim only works for one day, and obviously there are only 24 hours within a day. I'm wondering if that's normal or I need to do some further configurations?

Here are some settings I put in my config files which may help: 
1) My replanning strategy is: 0.7 for "ChangeExpData", 0.2 for "Reroute", and 0.1 for TimeAllocationMutator.
2) Since all my agents only have one initial plan and it only contains a "home-work-home" sequence, therefore, my setting for "mutationAffectsDuration" is false;
3) The network of my model takes place in Brussels, but I only used 0.5% of the total population (that is about 5000 agents in total). As a result, my config for flowCapacityFactor is 0.005, and the storageCapacityFactor is also 0.005 (I may increase this value due to the previous suggestions from the MATSim community).
4) The network I generated is from the OSM, and I followed the generation method of the 2020 MATSim guidebook (basically using OSMOSIS and RunPNetworkGenerator from the MATSim example). Therefore, I think my network has already been cleaned?
5) The coordinate system of my network is different from my plan, but I have set the coordinate transformation in my config "global" and respective module.

I hope these settings make you easier for tracking my problem :)

Thanks very much for your reading and help in advance!

**Comment by mrieser** [comment]
probably some agents got stuck, waiting for PT.

It's usually a good thing to set an end time for the QSim. In the `config.xml`:

```xml
<module name="qsim">
  <param name="endTime" value="30:00:00"/>
</module>
```

**Comment by jingjunL** [comment]
> probably some agents got stuck, waiting for PT.
> 
> It's usually a good thing to set an end time for the QSim. In the `config.xml`:
> 
> ```
> <module name="qsim">
>   <param name="endTime" value="30:00:00"/>
> </module>
> ```



> probably some agents got stuck, waiting for PT.
> 
> It's usually a good thing to set an end time for the QSim. In the `config.xml`:
> 
> ```
> <module name="qsim">
>   <param name="endTime" value="30:00:00"/>
> </module>
> ```

Hi Marcel, many thanks for your reply as always! I don't have PT in my network. I thought about this during the weekend, and I think the potential reason is all my agents are running by individual car, so the congestion in the city centre is very high and they got stuck. My next plan is adding public transport to see how it works. 

The tip for config file is something that I omitted, I will put that setting into my account. 

Cheers,
Jingjun

**Comment by kainagel** [comment]
Setting the qsim endTime to a finite value is a common trick ...

... but IMO it should not be over-used.  It aborts agents who have not finished their plans, and those aborted agents make analysis difficult.  E.g. assume that in the base case all agents with long distances are aborted because of endTime, in the policy case they make it within the time frame, then the average distance per traveller will go up only for that statistical reason.

So if you need to set the endTime, I would recommend to set it loose enough so that, in the relaxed situation, everybody has finished their plan by then.

Which means that if you have some problems getting travellers in or out to/from their facilities, you need to find some other way to resolve that.

(BTW, if you want to switch on mode choice, an easy way is to use teleportation, please read https://matsim.org/docs/userguide.)

(Or, even easier, if you want to get some intuition: If you have, say, a 2/3 car mode share, you could set flow and storage capacity factors to 3/2 = 1.5 in order to get some initial intuition if your demand/supply balance is approximately ok.)

**Comment by jingjunL** [comment]
> Setting the qsim endTime to a finite value is a common trick ... ... but IMO it should not be over-used. It aborts agents who have not finished their plans, and those aborted agents make analysis difficult. E.g. assume that in the base case all agents with long distances are aborted because of endTime, in the policy case they make it within the time frame, then the average distance per traveller will go up only for that statistical reason. So if you need to set the endTime, I would recommend to set it loose enough so that, in the relaxed situation, everybody has finished their plan by then. Which means that if you have some problems getting travellers in or out to/from their facilities, you need to find some other way to resolve that. (BTW, if you want to switch on mode choice, an easy way is to use teleportation, please read https://matsim.org/docs/userguide.) (Or, even easier, if you want to get some intuition: If you have, say, a 2/3 car mode share, you could set flow and storage capacity factors to 3/2 = 1.5 in order to get some initial intuition if your demand/supply balance is approximately ok.)

Thanks for the comment Kai! I'm currently figuring out how to add public transport in the Network of Brussels, so let's see what will happen when I have added them :)

Many thanks for your kind help as always!

Cheers,
Jingjun
