### ISSUE TITLE
After PersonEntersVehicle, agent gets stuck

### ISSUE THREAD

**Issue by yanlab19870714** [matsim-org/matsim-code-examples#394]
Hi there,

We are running a MATSim simulation but find a lot of vehicles stuck and abort at the end of the day... looking into one such vehicle, we find that after "PersonEntersVehicle" event, "VehicleEntersLink" event never happens till abort, or happens hours later.

We conjecture that the link to get the vehicle on could be congested, but after visualization, we do not find any congestion... do you know what is the cause? This happens to the afternoon Work-to-Home rides, and we have been stuck on this issue forever...

Also, how do you decide when a vehicle can get on its link ahead, after previous activity ends? The code is a bit complicated with many interfaces layered, so kind of difficult to pinpoint the location of the code that does it.

Thanks a lot!

Best,
Daniel

**Comment by jfbischoff** [comment]
It could indeed be a case of congestion, which sometimes is not properly visualised.
I would suggest setting:

`		<param name="insertingWaitingVehiclesBeforeDrivingVehicles" value="true" />
`

in QSimConfigGroup. This usually solves the problem.

**Comment by mrieser** [comment]
> It could indeed be a case of congestion, which sometimes is not properly visualised.

Indeed. Many visualisations interpolate a vehicle's position between its linkEnter- and linkLeave-Event timestamps. When the congestion is only on the last link, and there is never a linkLeave event on that link the vehicles usually cannot be visualized and thus the congestion is not visible.

On the other hand, if the congestion is only on a single link, and there is no spill back (e.g. the link is not full, although a lot of vehicle enters), then probably the links' attributes need to be checked (storage capacity too large, e.g. due to very long length or high number of lanes; or very low speed and they are not stuck, but just very very slow, ...).

**Comment by yanlab19870714** [comment]
Got it. Thanks!
