### ISSUE TITLE
ERROR AbstractTransitDriverAgent:280 java.lang.RuntimeException: Transit vehicle is not yet at last stop!

### ISSUE THREAD

**Issue by vsgo222** [matsim-org/matsim-code-examples#415]
Dear Community,
I am trying to run a before and after scenario for a city where base scenario has "x" number of PT frequency and in the after scenario the PT frequency are either or decreased depending upon the number of PT ridership (top 25% routes double their frequency and others reduce their daily frequency to maintain constant Vehicle Revenue Hours (VRH)). I also introduce a bus exclusive lane on these top 25% routes. 
I want to compare the effect of increased PT and bus lane on the road network. 
I have coded the relevant transitSchedule, transitVehicle and network.xml file to reflect these conditions. 
When I run this conditions in MATSim it throws an error "ERROR AbstractTransitDriverAgent:280 java.lang.RuntimeException: Transit vehicle is not yet at last stop! vehicle-id = veh_114_bus; next-stop = citycast-gotransit__28425.link:1127325414"
Can anybody help in debugging what could be the possible source of this error and what should I be doing to avoid it? 

Sincerely
Vedant
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/5098633/logfile.log)

**Comment by vsp-gleich** [comment]
Hi, the error seems a problem with your TransitSchedule (just look in code when that line 280 in AbstractTransitDriverAgent can occur). You have NetworkRoute for a TransitRoute which ends before reaching the last stop. Then the simulation complains that the transit vehicle did not reach the last stop of the line. So check your TransitSchedule. [TransitScheduleValidator](https://github.com/matsim-org/matsim-libs/blob/master/matsim/src/main/java/org/matsim/pt/utils/TransitScheduleValidator.java) finds some common errors.

Besides, if you want to analyse the effect of changes in bus frequency, please take into consideration that if you enable the strategy TimeAllocationMutator, passengers can adapt their departure times to the transit schedule if the following activity is not constrained enough by latest arrival times or similar. Therefore effects can be smaller than expected, because only transferring passengers have significant time savings (less waiting time for connecting buses).

**Comment by vsgo222** [comment]
This is resolved. I modified my code a little bit to bring changes to corresponding link, stopFacility and stop attributes both in TransitSchedule and Network.xml file. Thank you!
