### ISSUE TITLE
Slow vehicle behavior

### ISSUE THREAD

**Issue by jalal1** [matsim-org/matsim-code-examples#417]
Hi, 

I am trying to run the car-sharing example from matsim-libs. I didn't change anything yet, as I am trying to understand how it works. There is a behavior that I don't understand, that when one of the vehicles enters a link, it is slower than other vehicles. I noticed it happened only where there is a vehicle in the link, and then another vehicle enters the same link.

Using Via as shown below, the capacity of the link is 10 and the flow capacity factor is 1. The first vehicle goes with a good speed ( seems to be the free flow speed ), but the other vehicle is going slowly and shown in orange. 

![image](https://user-images.githubusercontent.com/1554493/90849467-eb144480-e334-11ea-91b8-5380f19ebe3f.png)

I really appreciate any explanation. 

UPDATE: The slow behavior is not related to car sharing. See the answers below. 

Thank you, 
Jalal

**Comment by mrieser** [comment]
This is due to the link (flow) capacity. Basically, the flow capacity specifies how often a vehicle can leave the link. If one vehicle has left the link, the next cannot leave earlier than a certain amount of time (e.g. a road with flow-capacity=1800veh/h equals to one vehicle every 2 seconds, in a 10% sample it would be every 20 second).

What you likely observe are two vehicles entering the link quickly after each other. The first can drive with free speed and leave the link, while the second one will have to wait some time until it can leave due to the flow capacity. So it spends more time on the link, which results in the slower speed in the visualization. The visualization just interpolates the vehicle's location between the linkEnter- and linkLeave-timestamps.

This is unrelated to car sharing and just a standard behavior of the MATSim simulation and Via visualization.

**Comment by jalal1** [comment]
Thank you Marcel, It is clear now!

It is indeed not related to car-sharing, but because I started with a car-sharing example and see this behavior. I will change the issue title to make it clear.
