### ISSUE TITLE
Activity on Links

### ISSUE THREAD

**Issue by helgehr** [matsim-org/matsim-code-examples#424]
Hello,

I have a conceptional question. At the moment I try to set up a bimodal transport simulation (with drt and pt).
For that I first simulated a normal public transport simulation on a grid and I noticed that the activities take place on network links and not on the nodes.
I think the former would be more intuitive, because I understood the links as roads and the nodes as the origins/destinations of individual trips.
This leads to somewhat strange routing because the agents do have to go to a specific link (specific direction) to start/finish their trips and not to the individual nodes.

Can you explain to me if I misunderstood something and if there exists a possibility to let the activities take place on nodes?

Thanks!

**Comment by mrieser** [comment]
You are correct, trips in MATSim start and end at links.

It is modeled after the reality, where in most cases, vehicles enter the traffic system by a driveway located along a link, or a parking space along a link, but they rarely just pop up in the middle of an intersection and start driving. Due to MATSim having unidirectional links this indeed implies that agents might need to do a U-turn in order to arrive at their destination.

If this behavior or the other is more intuitive is hard to say and I'm sure, different opinions exist about it.

It it really troubles you, you could add special, short "driveway" links to your model and make sure that only those are used as activity locations. You would end up with a high number of additional short links (which will use additional memory in the simulation), but you could then add nodes at the appropriate location of longer links, so vehicles could actually turn into the driveway coming from both directions.

**Comment by helgehr** [comment]
Ok, thats good to know. Thank you very much!
