### ISSUE TITLE
leg mode vs. routing mode

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#487]
Hi,

I am looking into my output_plans file. In some cases, leg mode is walk however routing mode is car:

leg mode="walk" dep_time= "19:00:10" trav_time= "00:17:00">
attribute name="routingMode" class="java.lang.String">car</attribute

in other cases leg mode and routing mode are both walk:

```
<leg mode="walk" dep_time="17:32:19" trav_time= "21:27:42">
  <attribute name= "routingMode" class="java.lang.String">walk</attribute>
```

I was wondering what is the difference between these two cases? what is the difference between leg mode and routing mode in general? for calculation of mode stats which one of the leg mode and routing mode is used?

Thank you in advance for your help.

**Comment by mrieser** [comment]
`routing_mode` is a newer addition to legs. In some cases, routers could not calculate a route for the requested mode. E.g. the transit router could not find a route in the middle of the night. Or a car-router cannot find a route to an island, if it's not connected with a bridge. In such cases, instead of returning no route which might lead to problems later on in the simulation, the routers fall back and usually provide a walk-route that will be teleported by MATSim. But this leads to a problem: The plan started with a pt-leg, but ends up with a walk-leg. In the next replanning, such a walk-leg would have been handled by the walk-router, and not the pt-router as originally intended. This is where the `routingMode` comes in: It specifies what router should try to calculate the route, ignoring the actual leg-mode.

So, the leg-mode is information for the mobility simulation, how to simulate the route. The routing-mode is an information for the replanning, how to calculate a new route the next time this leg is replanned.
