### ISSUE TITLE
avg. score statistics per leg mode

### ISSUE THREAD

**Issue by Alnik89** [matsim-org/matsim-code-examples#519]
Hi everyone,
in my current thesis, i am trying to evaluate different mobility concepts in a model region in schleswig holstein.
Since im not very well versed in java coding i wonder how to analyse the different score statistics of the different leg modes in my model (car, pt, drt).
Is there any quick and dirty code solution to get the average score statistics per leg mode?
Or even more simple is there any config adjustment which i have probably overlooked in my research for a solution to my issue?

In advance,
Many thanks for any help!
Kind regards
Alexander

**Comment by Alnik89** [comment]
Since I have now stumbled across the "writeExperiencedPlans" option.
To put my original question in concrete terms:
I just want to analyse the cumulative evaluation results (of S_wait and separate S_late) of the respective leg mode.
Is my request basically possible and what should i consider when writing a controller listener?

**Comment by jfbischoff** [comment]
The experienced plans are a nice tools for evaluation. IIRC, score stats are also written out with them into the iteration folders, so that is definetly one starting point.

Also, there are CSVs (of persons, trips and legs) which may be easier to analyze. These are typically stored in the output folder. You can extend these CSVs relatively easily with your own data, as they come with a customizable extension interface.

**Comment by Alnik89** [comment]
Thank you for that hint.
I will deal with it.
Many thanks.
Greetings
Alexander
