### ISSUE TITLE
Create new PT vehicles & new departures in transit schedule

### ISSUE THREAD

**Issue by gammapopolam** [matsim-org/matsim-code-examples#530]
Hello!

Is it possible to create new PT vehicles and new departures for it in transit schedule along with new iterations? 
For example, there is only one departure in 08:00:00 in input, so it should be more departures (08:30:00, 09:00:00 etc) to transport the agents in next iteration

**Comment by vsp-gleich** [comment]
Yes, it is possible. You can modify the schedule and the transit vehicles between iterations. You have to throw a TransitScheduleChangedEvent to force the router to update its schedule information and that only helps with routing thereafter. Please note that agents can keep their pt routes from previous iterations, so they might continue to take another line because they don't know line 1 now has more convenient departures. E.g. the minibus contrib uses all that functionality.

**Comment by gammapopolam** [comment]
I forgot to mention that the new departures should be created automatically. Is this method exists right now?
What should I add to my config to modify the schedule between iterations? Or should I use Java to change the schedule?
Sorry for asking this kind of weird questions.

**Comment by vsp-gleich** [comment]
There is no automatic creation of new departures, yet. You have to implement yourself in Java.

**Comment by gammapopolam** [comment]
Thank you!
