### ISSUE TITLE
How to find and solve null link length?

### ISSUE THREAD

**Issue by subrina0013** [matsim-org/matsim-code-examples#587]
Hello Everyone
I am trying to simulate traffic on car and pt (bus and subway) but the network I am using gives me error that it has null link length (WARN LinkImpl:125 length=0.0 of link id 101259 may cause problems). I am wondering  what to do with that? I am having few other issues and thus have some additional questions.
1. Find and solve null link length problem.
2. Why my gtfs-merger is using some of the gtfs files and not all while creating the network?
3. Is subway/metro always an artificial link? Can i also simulate traffic and do analysis on metro along with bus and car?

I really appreciate your suggestions.
Thanks

**Comment by Janekdererste** [comment]
1. Assuming you used an automated convertion method to create your network, I'd suggest to run your scenario and check whether this link with a length of 0 causes problems. Most of the time it doesn't. 
2. Which gtfs converter are you using and which files are not used, or what information do you think is missing in the generated schedule?
3. If you use an automated gtfs-to-matsim-schedule converter the pt usually runs on separate links. It is possible to let the pt run on the same links as other traffic, this requires to connect the stop facilities of your schedule to the existing network, as well as changing the network routes of your transit routes so that those use the car network. 

You could refer to chapter 16 of the [user guide](http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf) which provides a lot of information about pt in MATSim.

**Comment by subrina0013** [comment]
Thank you so much for your reply. 
   1.The error just says "Cannot invoke "org.matsim.api.core.v01.network.Link.getLength()" because "link" is null while locating SwissRailRaptorFactory". How to debug exactly which link is causing problems?
   2. I am using gtfsmerger in python (https://pypi.org/project/gtfsmerger/). I am trying to merge 5 gtfs files from different county. Two of them were merged but the rest were not in the merged file. Also, the network i created with this merged file, gave the same error of null link length.
   3. Doesn't the default pt2matsim setting connects stop facilities to the network? In Via, the green links are pt but also allows car. So, are they considered as pt separately or along with car?
   
![Capture](https://user-images.githubusercontent.com/42855310/125378449-c1a14480-e35c-11eb-8d0d-515d19ba8de6.PNG)

   4. When I tried to use pt as leg mode, it was running endlessly for a  specific  vehicle (bus). Why is that? What I can do to solve it?

I know I am asking many questions, but any suggestion would be really a very big help.

**Comment by Janekdererste** [comment]
1. You could set a break point at the line number from the error message to see where the error happens and which link is null. Also, please note, that the code crashes because the value of a link is 'null' this is a special value in Java, which means 'nothing is there'. The program then tries to query the length of that nothing and crashes. This means your problem is not, that the length of a certain link is 0m but a link, which is referenced from your transit schedule, can't be found in your network. 
2. Unfortunately, I don't know this program. It would be helpful to see a logfile or a stack trace of that error because I don't really know what you mean, when you say "the network ... gave the same error..."
3. I don't know about pt2matsim maybe @vsp-gleich can shed some light here. Our other utility for converting gtfs to matsim input data requires a separate ```createPseudoPtNetwork``` for the pt connections to be included in the network. 
4. Pt dosn't need to be specified as network mode ( I guess that's what you meant) An explenation of how to have pt on the network is in the user guide chapter 16 (link above)

This seems to be a sophisticated set up. It would be helpful to have a link to a repository and the files you've produced to give more helpful tipps.

**Comment by vsp-gleich** [comment]
>     3. I don't know about pt2matsim maybe @vsp-gleich can shed some light here. Our other utility for converting gtfs to matsim input data requires a separate `createPseudoPtNetwork` for the pt connections to be included in the network.

At vsp we usually use  different gtfs converter so there is not much I can say about pt2matsim. As far as I know it can be set up in various ways, matching stops to the car network or not. Probably you have to provide more information about your pt2matsim settings so someone (maybe @polettif ) can help you.

**Comment by polettif** [comment]
I'd like to reiterate @Janekdererste's point that this issue is hard to solve since we don't know any settings, log files or  how the workflow is set up. Also, it looks like there are multiple issues at play here.

pt2matsim's `GtfsConverter` just converts a GTFS feed to a MATSim schedule (without stop links and link sequences) and the parameters there are pretty limited. The converter doesn't do any network matching, this is done with `PTMapper`.

> Can i also simulate traffic and do analysis on metro along with bus and car?

Yes, that's possible but it depends on the PTMapper config.

**Comment by subrina0013** [comment]
Thank you so much.
