### ISSUE TITLE
Rejected requests in DRT

### ISSUE THREAD

**Issue by elyh1992** [matsim-org/matsim-code-examples#591]
Hi,

I have some questions about the DRT extension. What happens to people that their DRT requests have been rejected? Do they get stuck and can't complete the rest of their plan? Does this make their score very negative and reduce the chance of selecting DRT again in the next iteration? 

Thank you for your help.

**Comment by michalmac** [comment]
If a request gets rejected, the agent's state is set to `ABORT` and the agent is removed from the simulation. This behaviour is implemented both in the `DefaultPassengerEngine` and `TeleportingPassengerEngine` (so-called dvrp/drt speedup mode where passengers are teleported instead of being physically transported).
