### ISSUE TITLE
Missing repo causes build error

### ISSUE THREAD

**Issue by pimajor** [matsim-org/matsim-code-examples#60]
Building the maven project from commit 63fca7c fails because the geotools dependencies are not on mavencentral:

Failed to execute goal on project matsim-example-project: Could not resolve dependencies for project org.matsim:matsim-example-project:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.geotools:gt-main:jar:14.0, org.geotools:gt-referencing:jar:14.0, org.geotools:gt-shapefile:jar:14.0, org.geotools:gt-epsg-hsql:jar:14.0: Could not find artifact org.geotools:gt-main:jar:14.0 in libs-release (XXXX) -> [Help 1]

Adding the following lines to the repositories list fixes the problem:
                <repository>
                    <id>osgeo</id>
                    <name>Geotools repository</name>
                    <url>http://download.osgeo.org/webdav/geotools</url>
                </repository>

**Comment by kainagel** [comment]
Right.  Just added it on github.  Repository locations are not transitive, so even if this is given in some upstream pom.xml, that info will not be used.  It probably has worked for many people anyways since they presumably have downloaded geotools anyways.  For example when installing matsim-code-examples as well.  However, it should clearly also work by itself.

On 28. Dec 2018, at 08:16, pimajor <notifications@github.com<mailto:notifications@github.com>> wrote:


Building the maven project from commit 63fca7c fails because the geotools dependencies are not on mavencentral:

Failed to execute goal on project matsim-example-project: Could not resolve dependencies for project org.matsim:matsim-example-project:jar:0.0.1-SNAPSHOT: The following artifacts could not be resolved: org.geotools:gt-main:jar:14.0, org.geotools:gt-referencing:jar:14.0, org.geotools:gt-shapefile:jar:14.0, org.geotools:gt-epsg-hsql:jar:14.0: Could not find artifact org.geotools:gt-main:jar:14.0 in libs-release (XXXX) -> [Help 1]

Adding the following lines to the repositories list fixes the problem:

osgeo
Geotools repository
http://download.osgeo.org/webdav/geotools
