### ISSUE TITLE
 Public transport transfer

### ISSUE THREAD

**Issue by china-shuai** [matsim-org/matsim-code-examples#614]
Hi, I'm trying to do a simulation of public transport larger than the city. There is a great distance between different stations. So I need to set a longer transfer distance in congfig.xml. Can the transportation modes other than "walk" be set to enable passengers to transfer between different stations, like "car"？
Thanks very much!

**Comment by vsp-gleich** [comment]
Hi, walk is the only available mode to transfer between 2 public transit services. A trip pt -> car -> pt is currently not feasible, because there is no router which could generate such a route. You could try to write such a router, but I would not recommend to do so (difficult and much work). Generally it is questionable whether this is a realistic option in real life, likely you would need to rent a car for the trip between the two pt services. Then why not use the rented car or your own car for the entire trip?

**Comment by china-shuai** [comment]
Thank you for your answer. My research scale is the scope of urban agglomeration. Sometimes, some passengers cannot reach their destination directly by public transport. He will take public transport to a larger city, and rely on the city's more perfect intercity public transport to further travel to his destination. I want to simulate this process. In China, under this spatial scale, private car travel is not welcomed by many people. Bus, train, high-speed railway and plane are still the main modes of travel.

**Comment by china-shuai** [comment]
I have another question. Will matsim change the "trip" used by "PT" in the simulation process. For example, from bus 1024 to train 2048. Thanks very much!

**Comment by Janekdererste** [comment]
> I have another question. Will matsim change the "trip" used by "PT" in the simulation process. For example, from bus 1024 to train 2048. Thanks very much!

I'm sorry, but I don't understand your question

**Comment by china-shuai** [comment]
> > I have another question. Will matsim change the "trip" used by "PT" in the simulation process. For example, from bus 1024 to train 2048. Thanks very much!
> 
> I'm sorry, but I don't understand your question

Excuse me, I mean, can matsim simulate the competition between different modes of public transport？
