### ISSUE TITLE
StorageCapacityFactor for 100% population

### ISSUE THREAD

**Issue by sashigurram** [matsim-org/matsim-code-examples#62]
This has been a bit of enigma for me for some time now. Dr. Nagel provided a comprehensive answer to the question on setting flow capacity and storage capacity factors (I believe this was answered in confluence and archived [here](https://github.com/matsim-org/matsim-code-examples/wiki/faq-48955430)). Per his answer, when using a sample population set the storage capacity factor to (flow capacity factor)^0.75. Thus when we use a 1% sample, the flow capacity factor = 0.01 and storage capacity factor = (0.01)^0.75 = 0.03. He also suggested setting Flow and Storage capacity factors to be 1 when using 100% population. In contrast, the article [here](http://www.strc.ch/2014/Horni_Axhausen.pdf) suggested using a storage factor of 10.

I tried 2 versions of this and it seems to be giving me very wierd results. As seen below, using storage capacity 1 seems to continuously increase the enroute persons since the AM peak and only drops after the PM Peak. At 24 hours, there are still a substantial number of people enroute. This is obviously very wrong. Although this behavior seems to get better when I used storage capacity factor of 3, the results still look off (still too many persons enroute at 24 hours). **Given this, can you please provide a fresh insight on the appropriate value for storage capacity factor?** At this point, it seems like I should set the storage capacity to higher than 3. **Can I just set it to 10 and be done with it or should I increment it by 1 and check results at every step?** **Moreover, how would setting the storage capacity to a very high value (lets say 10) affect the results?** The trend seems to be definitely getting better with a higher storage capacity factor.

**Additional Background:** I am using matsim 0.9.0 for these runs and am simulating car (as network mode), ride, bicycle, school bus, and walk modes (these are all teleported), along with public transit. I also am including toll links and implemented the road pricing module in this scenario.

**_With Storage Capacity = 1:_**
![10 leghistogram_all_storag1](https://user-images.githubusercontent.com/16829703/50543774-c9d67180-0bae-11e9-89b1-49d90b74bd22.png)

**_With Storage Capacity = 3:_**
![10 leghistogram_all_storag3](https://user-images.githubusercontent.com/16829703/50543784-dd81d800-0bae-11e9-8c1e-2f7de5bcfce6.png)

**Comment by kainagel** [comment]
I don't think that there is a "final" answer.  I assume that you are running 100% scenarios, i.e. all these factors should be "1".  Storage capacity is then computed as lengthOfLink*numberOfLanesOfLink/7.5m.  I would say that this is a roughly realistic number (if you want to have mixed vehicle types, you could set PCU values there, but that is not the issue here).  If, for whatever reason, results are weird with these numbers, then I would say that there is something wrong, either in the matsim logic itself, or in the specific scenario.

We have also looked at network breakdown some time ago, see here: https://link.springer.com/article/10.1140/epjb/e2008-00153-6 , also referenced by the Horni/Axhausen paper.  Since then, the MATSim logic has been made more deterministic, and the issue of network breakdown has become smaller (in my observation).  We (in Berlin) have never worked with storage capacity factors >1; we have even found that with the now more deterministic logic, I would now recommend storageCapacityFactor = flowCapacityFactor, other than what we have recommended in the past.

However, what we _do_ find are situations where demand is higher than what the network can process.  This seems to be your situation, and the Horni/Axhausen situation looks like that, too.  As soon as you have mode choice switched on, that excess demand is often squeezed into some alternative mode, especially if that alternative mode is not capacity constrained.  One indicator for this is the bias line in the biasErrors plot; the blue line in the following (a non-calibrated illustrative run):
![biaserrors](https://user-images.githubusercontent.com/8777649/50605064-69eb0e00-0ec1-11e9-9afc-a65f20603203.png)
In that plot, there is "too much" traffic around 5am, and "not enough" around 8 and 19 to 21.  The leg histogram looks a bit similar to yours:
![run305 700 leghistogram_all](https://user-images.githubusercontent.com/8777649/50605198-de25b180-0ec1-11e9-9f54-39a7ad7f0cfb.png)
I.e. the traffic having problems getting out of the system.

It could potentially be the case that you have close to zero bias, but there is still mismatch, e.g. when you are ignoring too much capacity which is normally on the minor roads but you have removed them.  I have seen it several times that that seemed like a convenient explanation but it was not the real reason; the real reason instead were either wrong (flow) capacity numbers for (some of) the links, or some error on the demand side (i.e. neglecting that people are sometimes sick, on holidays, on different work-related travel, ...).

Could you add a VIA or OTFVis plot of your traffic dynamics?

Finally, having said all this, it is true that one can construct unstable situations when the storage capacity is "too" small; see, e.g., 
https://doi.org/10.1287/trsc.32.1.3 .
