### ISSUE TITLE
Modes in MATsim

### ISSUE THREAD

**Issue by MahsaSiegrist** [matsim-org/matsim-code-examples#627]
Hello all,

I would like to know how modes are modeled in MATSim and considered by travelers?
For example, for traveling from X point to Y point, if both bus and train exist, do some agents prefer bus over train?

**Comment by kainagel** [comment]
In general, MATSim agents will try all different modes eventually.  (As configured by the corresponding strategy, e.g. ChangeTripMode.)

However, for the specific example you mention, they will both be absorbed into the "pt" = public transit mode.  For the pt mode, the pt router will return one option as the preferred option.  If that router is asked again, with the same departure time, it will return the same answer.  When asking with a different time (e.g. caused by time mutation), the answer may be different.  I can see that the pt router should be less deterministic here.  We have experimental versions that achieve that (to, e.g., force a "travel by train" in a case where an airplane would be much faster), but they are not in a state that we can make them available without causing many headaches.
