### ISSUE TITLE
How to compute travel time when I change the speed of links?

### ISSUE THREAD

**Issue by wyj1234** [matsim-org/matsim-code-examples#633]
Hi,I am trying to use the Time-Dependent network for example modelling congestion in some period by changing the speed of all links during this period while I found that by using
`Network network = inject.getModal(Network.class);`
I get a network that is not Time-Dependent.I was thinking the Time-Dependent network didn't work until I found that many taxis didn't arrive their destination in time.
So I realize that the network in Simulation is Time-Dependent, however the travel time it computes is still according to the freespeed unchanged.
How can I get the travel time acroding to the speed I changed?
Thank you!
Best,Yujie Wang.

**Comment by michalmac** [comment]
Depending on how you configured your simulation, it can be either time-dependent (i.e. network parameters change over time) or time-independent (i.e. network params are fixed).

Having a time-independent network does not mean the travel speed are fixed. They can change as traffic changes over time.

In the default taxi contrib, we monitor the traffic and the travel times are updated after each iteration. But getting right estimates requires running many iterations, while the initial estimates assumes no traffic (free speeds)/ That's why you probably observe lots of taxis arriving late. This should improve after running more iterations.

**Comment by wyj1234** [comment]
> Depending on how you configured your simulation, it can be either time-dependent (i.e. network parameters change over time) or time-independent (i.e. network params are fixed).
> 
> Having a time-independent network does not mean the travel speed are fixed. They can change as traffic changes over time.
> 
> In the default taxi contrib, we monitor the traffic and the travel times are updated after each iteration. But getting right estimates requires running many iterations, while the initial estimates assumes no traffic (free speeds)/ That's why you probably observe lots of taxis arriving late. This should improve after running more iterations.

**Comment by wyj1234** [comment]
Thank you a lot!
