### ISSUE TITLE
PT agents

### ISSUE THREAD

**Issue by SarahSie** [matsim-org/matsim-code-examples#636]
Hello,

For my analysis, in the last iteration of running, I need to distinguish between PT agents (agents who use public transport), Car agents (agents who use car mode for their travel), and walk mode agents (those who only use walk mode to travel between their activities). I would like to know the quickest and most efficient way to identify PT users from others?

Thanks in advance.

**Comment by vsp-gleich** [comment]
Hello,
this is probably not feasible because the same agent can use walk, pt and car on the same day. So there is no clear distinction between pt agents and walk agents possible. The closest is maybe to look into the trips.csv and implement your own distinction like "agents using pt at least on one trip" and "agents using car at least on one trip" and those groups will likely overlap.
