### ISSUE TITLE
Which types of plans can Matsim use

### ISSUE THREAD

**Issue by Warkcs** [matsim-org/matsim-code-examples#673]
Hello,

I am new to Matsim and I am trying to create a xml population file. When I had to assign the type to the plans, i was thinking to use shopping, leisure, work, medical, carry and education as types, but when i tryed to search at the Matsim book if this types are valid  i couldn't find it. Could someone help me?.

Thank you so much.

**Comment by JWJoubert** [comment]
Hi @Warkcs, the MATSim book is not prescriptive about what those types must be. You have to make sure (yourself) that the activity types included in your plans are also specified in the `config` - specifically the scoring parameters for activities.  Otherwise the MATSim machinery will not know how to score them at the end of an iteration. Consequently, it will crash (but the error message will most likely hint to exactly that)

**Comment by Warkcs** [comment]
Thank you so much for your quick answer. It was very helpful :)
