### ISSUE TITLE
Irreducibility

### ISSUE THREAD

**Issue by KamijoYo** [matsim-org/matsim-code-examples#69]
Hello everyone. I have two questions about irreducibility. 

As for the first question, is irreducibility satisfied even when "fractionOfIterationsToStartScoreMSA" is turned on?

As for the other question, I suppose that MATSim currently updates the link cost of each link on every iteration, but if you use the average value of the link cost for the previous five iterations instead, would it be a 5th-order Markov chain and would irreducibility still persist?

**Comment by kainagel** [comment]
I take irreducibility as "a non-zero probability of transitioning (even if in more than one step) from any state to any other state" (wikipedia).  This first depends on your state space definition.  One thing that is useful is to switch off innovation (which we recommend together with the MSA thing that you mention).  Then each agent has a fixed number of plans (fixed choice set).  Now, each combination of plans (where each agent selects one plan) can be reached, so this is irreducible/ergodic.  If you do not switch off innovation, then the system may keep generating new plans, thus enhancing the state space.  Alternatively, you could try to define the space of all _possible_ plans.  I can't say anything about irreducibility in that space.

Once you have switched off innovation, you can also try to force the scores to converge.  This is what the MSA switch is doing.  Once scores are converged, plan selection probabilities are fixed, i.e. no longer depending on the previous iteration.  Which implies that without that it is not even Markovian if your state space is the index of each selected plan.  I don't know what happens if you absorb agent scores into the state space, but then your space becomes mixed discrete (plan choice)/continuous (score).

We tried to write this up here: https://books.google.de/books?hl=en&lr=&id=uIwWBAAAQBAJ&oi=fnd&pg=PA261&ots=FsTBk6h3sY&sig=JS-rvMpjicOMTVtPTtDvjWbzyGc#v=onepage&q&f=false (you can find preprint versions on the web).

**Comment by KamijoYo** [comment]
Thank you very much for your reply.
I have read the corresponding chapters 46 to 49 on the paper "The Multi-Agent Transport Simulation MATSim", but I'd like to confirm that my understanding below is correct. 

On page 329, chapter 48, the Markov chain is described in a large framework. The state space of the agent's schedule group Z defined on that page is irreducible after the innovation switch is turned off, and hence becomes ergotic and converges to a stationary distribution. However, the schedule' score cannot be added to the state space because it is continuous.
In practical use, the MSA is used because the above-mentioned Markov chain has a large number of states and the transition probability of Z is complicated, so it takes time to converge and for a steady distribution to be achieved quickly.
