### ISSUE TITLE
Is it possible for an agent to stay home in exchange for a monetary compensation? 

### ISSUE THREAD

**Issue by cedricvdbd** [matsim-org/matsim-code-examples#703]
Hello,
for my master's thesis I'm trying to simulate negative tolling; giving agents a monetary compensation in exchange for them not to take the car and stay home (during peek traffic). The idea comes from the Netherlands (https://nl.wikipedia.org/wiki/Spitsmijden). However, I have not seen any example project doing this. 
Can anyone please help me?

**Comment by kainagel** [comment]
If you are using a standard version of MATSim, you can throw money events, and they are multiplied with the marginal utility of money, and then added to the score.  So you could:
* at the beginning of the mobsim, give every agent some amount of money
* if the agent has a car departure during peak traffic, you give that agent the same amount of money, but negative (i.e. you take it away).

One immediately sees the problem that one also has in reality: One does not want to give the reward to everybody, but only to those that have used the car before during the peak hour, since otherwise it gets too expensive.  Which is wildly unfair, since why should we only give money to those people who have done undesirable things in the past?

Evidently, in MATSim you could go through all agents and find out if they are using the car in the base case.  And apply the treatment only to them.

If you know how to program into MATSim in Java, then this would be relatively easy, since it is only an `EventsHandler` which then by itself also throws an event.  Otherwise ... hm.  I don't know where you stand here; do you have some experience with Java and MATSim?

**Comment by cedricvdbd** [comment]
Hi Kai, 
thank you for the speedy reply. 

Indeed, I was looking at doing something like this; identifying agents who passed through some links during peek traffic hours and then try to change their behaviour by giving them money, which would impact their score. 

The implementation of this measure raises some eyebrows of course, but as a measure to temporarily reduce traffic during roadworks for example, it's something to be considered. 

As I didn't know MATSim before starting my thesis, I'm not at all acquainted with the software. I can understand written code (to some extent), but by no means write any code. Is there any option which would be relatively easy to code and put me on the way to do the full analysis?

**Comment by Janekdererste** [comment]
Our MATSim class starts on the 25th of April. This class will be held in hybrid format and is open to external participants as well. The material you need to understand in order to program your scheme will be taught between the 5th and the 10th week I would estimate. You can send me an e-mail (laudan@tu-berlin.de) if you are interested.
