### ISSUE TITLE
AStarLandmarks: Set number of landmarks

### ISSUE THREAD

**Issue by ChristophTraf** [matsim-org/matsim-code-examples#72]
Hi!

We are running simulations with many nodes. When using the AStarLandmarks algorithm the memory of our server gets full. Could somebody tell me how to reduce the number of Landmarks?

Thank you!

Settings: config.controler().setRoutingAlgorithmType(ControlerConfigGroup.RoutingAlgorithmType.AStarLandmarks);
Set number of Landmarks???

**Comment by mrieser** [comment]
The number of landmarks is currently hard-coded (16) and cannot easily be changed by configuration.
Are you sure that the memory gets full due to the landmarks? In my experience, the AStarLandmarks-router is rarely the biggest memory hog. Even if you would be able to reduce the number of landmarks, you would very likely run into memory problems somewhere else. So I would first try to really understand what is using all the memory.

**Comment by ChristophTraf** [comment]
Thank you Marcel!
I`m not sure if the memory problem arises from the number of landmarks. We now use the FastDijstra instead of the AStar algorithm.
