### ISSUE TITLE
Question about Strategy definition

### ISSUE THREAD

**Issue by diallitoz** [matsim-org/matsim-code-examples#770]
Hi,
I am a little confused about the definition of strategy in MATSim. When I read the book and its 2022 extract (p. 13 and 36) http://ci.matsim.org:8080/job/MATSim-Book/ws/partOne-latest.pdf, it seemed that just some agents were authorized to change their plans (p. 13). However, on page 36, it appears that each agent can change their plan according to the weight of the strategies.

Can you please enlighten me on this point?

Best regards,
Azise

**Comment by JWJoubert** [comment]
Hi @diallitoz, the strategy is fully configurable. One of the _strategies_ is `SelectExpBeta`, which is the scenario where an agent selects from the current _pool_ of `Plan`s: the better its expected/scored performance, the higher the probability of being selected.

So, typically, the `SelectExpBeta` strategy will weigh around 70%-80%, while the other strategies will jointly add up to 20%-30% to make up the balance. The result is then what you described: only a _portion_ will really _replan_ (the 20%, like rerouting, time mutation, mode choice, etc), and the bulk will only pick plans from prior iterations.  The VSP or IVT groups may chip in and explain the theory maybe, but the consensus is that no too many agents should be involved in (radical) replanning, otherwise you battle to get the simulation to converge to a steady state.

**Comment by diallitoz** [comment]
Hi @JWJoubert, 
Thanks for your response. 
I had this understanding indeed.

However, if 80% of the agents do not replan, this means that their plan does not change during the simulation, even if the scores can evolve from one iteration to another.
So, in this case, is it necessary to establish a strategy for them to select the "same plan"?

**Comment by JWJoubert** [comment]
@diallitoz 

> However, if 80% of the agents do not replan, this means that their plan does not change during the simulation

The strategy is applicable *per iteration*. So, it is not the *same* 80% that will not replan in the entire simulation. In each iteration, each person picks a “strategy” with some probability: 80% picking one of the current plans; 10% rerouting; 10% changing mode (or whatever your weighting is).

**Comment by diallitoz** [comment]
Ok, I see, and I thought it was the same agents that replanned during the simulation.
Therefore, the strategies weights define the portion of agents authorized to perform a replanning per iteration and the probability of realizing this change.
Thank you again, @JWJoubert .
