### ISSUE TITLE
I'm a beginner，could you help me write the config ？

### ISSUE THREAD

**Issue by GA18gua** [matsim-org/matsim-code-examples#775]
so I been having my 1st contact with MATSim. I’m surely reading the official book but it’s a slow process. I do get the philosophy of the program and what it provides etc but all I have been able to do until now is running the examples (EQUIL Berlin etc ) on MATSim GUI and do some visualisations with VIA.
So my questions are :
what are the areas of the book that I should read as a priority to make learning faster ?
can I modify manually things in the existing open source projects and how ?
Where does JAVA programming comes in handy or what does it accomplish ?
How do I prepare the required files in order the get an executable config.xml file ( Network, agents, plans etc… ) ?
Are there any step by step projects or tutorials from scratch here on github or other websites ?
any further form of help is so welcome.

**Comment by JWJoubert** [comment]
Hi @GA18gua, a colleague of mine has a very apt saying: _"any short term solution is a long term nuisance"_ 😉

I suggest your next step is two-fold:
1. Work through the [TU Berlin tutorials](https://www.matsim.org/docs/tutorials/general); and then
2. decide what the problem is that you want to solve. I do not think it is good practice (in simulation, generally) to have a tool, and then look for a problem. Decide what problem it is you want to solve, and **_that_** will/should guide you of which areas within MATSim you need to search/learn deeper (or not). MATSim is a **_huge_** and encompassing piece of machinery - I don't think you can/should try and master the whole before zooming into an area that is suitable for your problem at hand.

**Comment by GA18gua** [comment]
thanks for your answer.
I want to research a problem related to parking.And I am reading the user manual.For your answer here is a question：The identity of the tourist does not have permission to study matsim courses，or this link is invalid.
