### ISSUE TITLE
Interpretation of unshared distance vs distance plot?

### ISSUE THREAD

**Issue by vishalmhjn** [matsim-org/matsim-code-examples#79]
The following plot is generated when the matsim-maas simulation scenario is run. As I understand, the unshared ride distance should be less or equal to the total travel distance. However, In the plot some points can be seen above the line (unshared ride distance = travel distance). Can someone help me understand, In which case can unshared ride distance be greater than travel distance?

![97 drt_detours_drt_distanceplot](https://user-images.githubusercontent.com/42190624/52141401-e35b5500-2655-11e9-8860-6ac635b4de2b.png)

**Comment by michalmac** [comment]
Two possible (non-mutually-exclusive) explanations:

1. Shorter in time is not equal to shorter in space
For planning paths in DRT, the objective is travel time minimisation. If I am going from one side of the city to another one, instead of going through the centre (== shortest distance), the path may lead through some bypass road. However, if there is a passenger to be picked up downtown, the vehicle may be routed through the city centre. The distance will be shorter than the one for the unshared ride (taking the bypass).

2. Travel time predictions are inaccurate.
Unless you run DRT on an empty network (with no traffic), the actual travel time of a given path will be often different than the expected one. So even if the DRT trip was not shared, its duration could be longer or shorter than planned.

In general, effects of (2) will be smaller than of (1), so "travel time vs. unshared ride time" should be more informative.
