### ISSUE TITLE
package org.matsim.contrib.protobuf.events does not exist

### ISSUE THREAD

**Issue by ifle** [matsim-org/matsim-code-examples#8]
I try to build the matsim project in Intelij Idea on windows and have following error:
```
Error:(22, 42) java: package org.matsim.contrib.protobuf.events does not exist
```
What is missing?

**Comment by kainagel** [comment]
In general, we strongly recommend to run matsim by clone from https://github.com/matsim-org/matsim-example-project.  Then such issues should not happen.  One can still view the source code, but not modify it, which is good, because it is now a plugin architecture that should be fully configurable from the outside.

Beyond that: Your error message looks like a problem with the auto-generated source code.  For eclipse, there is a `Makefile` at `matsim/contribs/hybridsim`, but for Intellij this has never been necessary for me.  What about (stupid) things such as refreshing `pom.xml`, rebuilding the project, killing and restarting Intellij, etc.?  Also, sometimes, maven gets interrupted in the middle of something and leaves a somewhat corrupted state behind (implying that one needs to delete directories in .m2).

**Comment by ifle** [comment]
Thanks I will try to clean the project and .m2
