### ISSUE TITLE
Matsim Routing dont start at the exact location instead on the next node. Why?

### ISSUE THREAD

**Issue by svken** [matsim-org/matsim-code-examples#825]
Lets assume i have an agent who wants to travel from node 1 to node 2. 
But with this network the Agent doesnt start to Travel. 
It needs a third Node 3 in the middle between node 1 and 2 for him to start.

WHen i look into the the visualization in Simunto Via he also starts from Node 3 and not Node 1.

I use the Matsim Example Project, unfortunately i cant ask questions there.

Can somebody explain why this is happening? Thank you!

**Comment by mrieser** [comment]
Agents in MATSim always start on a link, not on nodes. Agents' activities are thus always connected to a link.

In your first example, where there is only one link, both activities get mapped to the same link. This is the reason why ultimately you don't see anything happen in that example, as it all takes place on the same link.

In your second example with two links, the first activity gets mapped to the first link (connecting 1 and 2), while the second gets mapped to the second link. Thus, the agent has to travel from link 1 to link 2.

In MATSim, an agent always has to travel along a full link. It is not possible for the agent to leave in the middle of a link, independent of the actual activity coordinate (due to technical reasons/implementation details). Agents can enter or leave traffic on a link always at the end of a link in MATSim. Thus, when starting from the first activity, it will start at the end of link 1, travel along link 2, and then leave at the end of link 2 for the second activity. This is the reason why you see it only traveling on link 2 in the visualization.
