### ISSUE TITLE
How to do a stopFacility mapping (locations and IDs) on an existing schedule?

### ISSUE THREAD

**Issue by MathieuCat** [matsim-org/matsim-code-examples#836]
Hello everybody,

I have used the pt2matsim library to generate a PT schedule from GTFS files and to map it to my network.
Nevertheless, the locations of the stop facilities are not accurate and the IDs are wrong, and I have another file that lists the correct locations and IDs of the stop facilities (not in GTFS format though).
I want to replace the stop facilities deduced from the GTFS files by the ones provided by that separate list.

How can I map the stop facilities from that list with the ones of the GTFS files?
Is there a function of pt2matsim or another library to do that mapping based on a criteria of proximity?

Thank you in advance for any help on that subject.

**Comment by Janekdererste** [comment]
The main library contains `NetworkUtils` if you have your facilities as nodes in the Network you can use `NetworkUtils.getNearestNodes(network, coord, distance);`

If you want to work with coordinates only, you can use a `QuadTree`, which is used internally by the mentioned method. You can put arbitrary items with a location into it and fetch it like this:

```
QuadTree<SomeClass> tree = new QuadTree<SomeClass>(minX, minY, maxX, maxY);
tree.put(locationX, locationY, someItem);
SomeClass closestItem = tree.getClosest(someX, someY);
```

Otherwise the [locationtech library](https://github.com/locationtech/jts/tree/master/modules/core/src/main/java/org/locationtech/jts/index) has multiple index implementations. This library is also included in matsim, so you should be able to use it if you have a dependency on the matsim project.

**Comment by MathieuCat** [comment]
@Janekdererste Thank you very much for your message.

Is there also a way to update the schedule file? I mean, it can be rather direct to update the stop facility locations because they are gathered in one unique list (transitStops), but it seems more difficult to update the stop facility IDs since they are "spread" in the file (in transitStops and in many routeProfiles).

I am thinking that maybe the most simplest way is to write a script that apply the mapping (locations and IDs) upfront, directly in the GTFS files, before calling pt2matsim.

**Comment by Janekdererste** [comment]
Yes, If you want to change Ids you have to make sure to update every place that has a reference to it. In a TransitSchedule this would be the `StopId` itself, as well as referencing `refId`s in `routeProfile`s. [Here](https://github.com/Janekdererste/matsim-serengeti-park-hodenhagen/blob/prepare_pt_for_class/src/main/java/org/matsim/prepare/CreateZooShutle.java) is an example how to use MATSim's Java API for altering Transit Schedules. This would probably easier than altering the schedule file directly.

Having things right in your data source is a good idea as well. However, I would advise to make this an automated process as well, since it is very likely that you want to update your schedule file at some point.
