### ISSUE TITLE
out of memory : out of java heap memory

### ISSUE THREAD

**Issue by Mayoookh** [matsim-org/matsim-code-examples#87]
Hello. 
 
I am trying to run a test case with 10% population , i.e. around 20,000 agents for a city on stand-alone MATSim application. I used pt2MATSim to create a network. I am working on a server with the following specifications :

1.  36 GB Memory
2. 3.4 GHz CPU

I assume this should be enough to run my test case but the memory still runs out, even before creating the network. (I have attached a picture with this message)

The compiler window shows the following message:
INFO TransitRouterNetwork:433 add transfer links

This is the last message before hours of compiling and then it runs out of memory. My task-manager shows 98% memory in use due to MATSim. Is there something I am missing here? Thanks for your help in advance. 

![error](https://user-images.githubusercontent.com/44500053/52862892-a5baf980-3136-11e9-99bc-8785194a9e08.jpg)

**Comment by jinkai89** [comment]
What coordinate system is your network and network files? It's preferable to use EPSG coordinate system instead of latitude and longitude.

**Comment by vsp-gleich** [comment]
Dear Mayoookh,
please have a look at the transit schedule you created with pt2matsim. Some transit agencies tend to publish very detailed GTFS-schedules in which many runs of the same transit line differ from each other, i.e. arrival/departure times differ slightly, the bus terminates one stop earlier than usual and heads to the depot or similar. MATSim has to split that transit line in one TransitRoute for each variation of arrival/departure times and stops served it encounters. Thereby you easily end up with hundreds of different TransitRoutes in the MATSim transit schedule even though the transit agency operates only 10 different "lines" (in the sense of names displayed as head sign on the vehicle).
If you use the old default Dijkstra-based transit router in MATSim (and the log file shown suggests that), you'll be unhappy with having many different TransitRoutes which have many transfer stops between them, because the router is slow at building the TransitRouterNetwork and uses lots of memory. The latter seemed to cause the exception you saw.

Try using the new transit router [SwissRailRaptor](https://github.com/SchweizerischeBundesbahnen/matsim-sbb-extensions) which is faster, uses less memory and can handle a high number of TransitRoutes.

If you still have problems, consider simplifying the transit schedule, i.e. replace multiple almost identical TransitRoutes with a single TransitRoute with more departures. We don't have any code ready for doing this, so you would have to write your own.
