### ISSUE TITLE
Change Location for A Specific Activity Type for Replanning, Is there Any Previous Example?

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#879]
We would like to set up a new replanning module so agents can change their locations during MATSim iterations. 

Let's say we now have an activity type called "leisure". In each iteration, we would like some agents who have leisure activities to change their location to another random potential "leisure" location within 1km. How should I achieve this? Is there any existing example of this? Thanks!

=========================================Update:

I know there is a `MyPlanStrategyModule` in https://github.com/matsim-org/matsim-code-examples/blob/11.x/src/main/java/org/matsim/codeexamples/strategies/pluggablePlanStrategyInCode/MyPlanStrategyModule.java. However, I really don't know how to change the `handlePlan` method as I don't know what should I return... Any comments?

**Comment by kainagel** [comment]
The general problem with "random" location choice in MATSim would be that, over the co-evolutionary algorithm and the scoring, the location would move ever closer towards the optimal location, which quite often would be directly at home or at work.  The problem is that in reality there are things pushing the location away ... e.g. there is a bar close next to your home but you prefer playing soccer as leisure activity.  In discrete choice modelling, this is the value of the epsilon: U = V + epsilon.  One would need to keep the epsilon "frozen" for each given combination of agent and facility.

To address this problem, there is the location choice contrib, https://github.com/matsim-org/matsim-libs/blob/master/contribs/locationchoice .  The readme is pointing into nirwana, but the code is actually in ok shape.   testFacilitiesAlongALine in https://github.com/matsim-org/matsim-libs/blob/master/contribs/locationchoice/src/test/java/org/matsim/contrib/locationchoice/frozenepsilons/FrozenEpsilonLocaChoiceIT.java would be a starting point.   A bit of an issue is that that contrib contains several functionalities on top of each other; the "frozen epsilon" functionality is exactly what models the frozen epsilon mentioned in the above paragraph.

There is also a description of this in the matsim book.

**Comment by jingjunL** [comment]
Thanks for your answer @kainagel . I see the point that there should be an fixed error term for location choice such as "leisure". However, my problem is relatively simpler: what if I only want to have the optimised location for the activity `leisure_soccer`?

Let's say I now have lots of agents, some of them want to do `leisure_soccer` activities in their plan (some not of course). Then, I have the location of all `soccer` facilities in my study area. Through some algorithms (based on the distances between each facility and the locations of remaining activities), I already assigned one `soccer` facility for each agent has a `leisure_soccer` plan, but the problem is that my algorithm cannot consider the real-time congestion effects of MATSim, so that in the simulation, some `soccer` facility will be so popular that it cause unreasonable congestion and delays. Even though there are other `soccer` facilities only 100m away, I cannot let my agents choose them because basic MATSim replanning does not have location choices.

So if I can just run MATSim simulation, let the agent change their `leisure_soccer` activities within a specific radius compared to present, and I think this will solve my problem.

Will this make the problem easier? Do you know any example for this? Thanks!
