### ISSUE TITLE
Contrib for Vehicle Ban Policy during Specific Hours

### ISSUE THREAD

**Issue by jingjunL** [matsim-org/matsim-code-examples#884]
I would like to model a scenario where the mode `car` is totally disabled in a specific area of my network during 8am to 4pm. This should be relatively easy to achieve as we just need to router to not route vehicles during the timeframe, so that agents will try to use `pt` or other modes. The most similar contrib I can think of is the `roadPricing` one, but it is still different. Is there other resources/works available? Thanks!

**Comment by Janekdererste** [comment]
Using Road Pricing and setting a prohibitively high toll would be one option as you have already guessed. The other option could be network change events, where you can change network properties during the simulation. [This](https://github.com/matsim-org/matsim-code-examples/blob/15.x/src/main/java/org/matsim/codeexamples/network/timeDependentNetwork/RunTimeDependentNetworkExample.java) could be a starting point

**Comment by kainagel** [comment]
A problem is that the car mode always starts/ends on the nearest link.  So if that has a high toll, then each car arriving/departing needs to pay that high toll.  If that link is completely closed, the car mode cannot arrive/depart.  (We often use very low speed/very low capacity instead of closing it completely.)

As so often, the way to address this starts in "planning", not in computation: You need to have some idea of how this is handled in reality.  Is it not allowed to part in the area around the clock?  Or not between 8am to 4pm?  (Does that mean people arriving after 4pm need to make sure that they remove their car before 8am?). One once those planning rules are clarified, can one think about an appropriate implementation.

**Comment by jingjunL** [comment]
Thanks for the reply, guys!

So for the planning element, people arrive in the area not during the restricted time can keep their car in the area, but they need to use other transport modes if they have other activities during 8am to 4pm. I don't see many problems there.

The network change event suggested by @Janekdererste sounds interesting! I think the best way would be to remove the `car` in the `allowedMode` for the links within the study area. I quickly mimic the code in example as attached:

`for ( Link link : scenario.getNetwork().getLinks().values() ){

            Set<String> allowedMode = link.getAllowedModes();

            if (allowedMode.contains(TransportMode.car)){
                NetworkChangeEvent event = new NetworkChangeEvent(7.*3600.) ;
                event.setLanesChange(new ChangeValue(HOW TO PROCEED WITH HERE?????? ));

            }

        }`

I don;t know how should I proceed with the `changeValue ` things because I think this is mainly for changing the numerical value? Do you have any idea? Thanks!

**Comment by kainagel** [comment]
I am not sure if setting the number of lanes to zero will do what you want.  In most cases, "(flow) capacity" takes precedence over "number of lanes".  The code may just increase the number of lanes (again) until the capacity value can be fulfilled.  --  One might think that there should not be a "number of lanes" setting.  However, a larger number of lanes, even with the same flow capacity, means a larger storage capacity.  Somewhat in general, one should not put in combinations of freeSpeed, numberOfLanes and capacity that are physically impossible.
