### ISSUE TITLE
Network : Curve Road Link in matsim

### ISSUE THREAD

**Issue by Matsim2022** [matsim-org/matsim-code-examples#895]
Hello community,

I would like to know the best way to represent the curve road links in MATSIM without creating too much overhead on run time by introducing too many shape nodes.

**Comment by JWJoubert** [comment]
If I understand you correctly, @Matsim2022, you want something _between_ the full network (which includes all the nodes and links) and the clean network where all possible links are fused using the `NetworkCleaner`, is that correct?

**Comment by Matsim2022** [comment]
Hi JWJoubert,

Yes, you are right. We need a network between a simple MATSIM network based on NetworkCleaner and the detailed OSM networks. The network simplification process removed some important features (e.g. the shape of complex junctions, curve links, etc.)  of the network.

**Comment by mrieser** [comment]
`NetworkSimplifier` (org.matsim.core.network.algorithms.NetworkSimplifier) provides an optional argument `tresholdLength`, which is set to +Infinity by default. It controls how long a link can be to be merged with adjacent links.

You could try setting it to some other value, e.g. to 300, in which case links longer than 300 meters should not be merged with other links, keeping some of the road geometry. But be aware that setting this parameter is discouraged, as the process is not deterministic (meaning: if the same original network is processed multiple times, different simplified networks may result).

**Comment by JWJoubert** [comment]
Thanks, @mrieser, that is what I had in mind - I just have not had the time to check whether it is still in the `matsim-up` repository or whether it was included in the `matsim` core. But there you have it, @Matsim2022, that allows you to achieve something along the lines of what you want. As Marcel rightfully notes, use it with caution... I was responsible for the original implementation, so that should say it all 😋
