### ISSUE TITLE
How to build the PARKing DATA to simulation,please

### ISSUE THREAD

**Issue by Cuiyi20** [matsim-org/matsim-code-examples#9]
Dear every,
In order to optimizing the parking price, where could I find a PARKING Example used in MATSim? I just want to konw how to prepare the input files such as Config.xml,parkingFACILITier.xml...,and so on.
Thank you very much!

**Comment by mrieser** [comment]
Have a look in these two directories: https://github.com/matsim-org/matsim/tree/master/contribs/parking/src/main/resources

**Comment by Cuiyi20** [comment]
Thank you,sir.
I have read the link content. But I still do not see the PARKINGCOST parameter setting.The two examples do not have obvious differences.At least I do not see it.Is there any other way to get some information?

**Comment by jfbischoff** [comment]
Hi, if you just want to simulate parking costs, you may want to  just write an Event Handler and throw money events. This might be more straightforward than using the parking choice contrib, for which a huge amount of additional data is required.

**Comment by whizkid-25** [comment]
Hi I  have a network incorporated with PT and car. In order to add a ride and park facility do I have to: 
(1) Add parking facility in the facility (xml) file as a new facility? Is there an example available? 
(2) Which strategy or module do I need to add in the config (xml) file to run the park and ride? 
(3) Do I need to make any changes in the plan file to facilitate the park and ride? 

It would be pf great help if you can direct me in the right direction. Thanks.

**Comment by whizkid-25** [comment]
Hi @jfbischoff and @mrieser  can you please help me in this regard?

**Comment by GA18gua** [comment]
Hi，@whizkid-25  ，do you made any progress？
