### ISSUE TITLE
Indoor pedestrian simulation, only set modes to walk

### ISSUE THREAD

**Issue by TanYun-1** [matsim-org/matsim-code-examples#949]
Hello, I am new to matsim. I am a graduate student and I will use matsim  to simulate indoor pedestrians. I need to set the mode to walk only, but now I get an error.(I changed the modes to walk in both config.xml and network.xml , but an error occurred) 
I don't know what to do, can anyone help me?

**Comment by JWJoubert** [comment]
Hi @TanYun-1. While you can _make_ MATSim do what you want, I doubt it is the appropriate tool for your job. MATSim was, as I understand it, meant for large-scale transport systems, so it (by design) lacks the spatial detail and movement dynamics that you will need to get a good pedestrian model. Other models might suit your application better, for example, [AnyLogic's](https://www.anylogic.com) pedestrian library. 

Regarding your error, you must check that the mode (walking) you allow on the network is consistently described in the mode parameters (`modeParams`) in the config file's `planCalcScore` and `plancalcroute` modules.

**Comment by TanYun-1** [comment]
Hi @JWJoubert   Thank you very much for your reply. 
First, I will think carefully about your suggestion and choose the right software for my research. 
Secondly, regarding my previous question, I followed your advice and changed the modes to walk in the network file, and changed the modes to walk n the config file's  planCalcScore and planCalcroute modules , but still got an error. I provide my file, can you show me where the error occurs?
Thank you again for your help！

[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/11573424/logfile.log)
[config.zip](https://github.com/matsim-org/matsim-code-examples/files/11573437/config.zip)

**Comment by mrieser** [comment]
First: You are using MATSim 13.0, which is 2 years old. Please update to the newer MATSim 15.0 if possible.

In your `config.xml`, you should keep modeParams for "pt" and "car", even if you don't use them.

Add the following lines to the `planCalcScore`-module, they can be empty so that default values are used:

```xml
<parameterset type="modeParams">
  <param name="mode" value="pt"/>
</parameterset>

<parameterset type="modeParams">
  <param name="mode" value="car"/>
</parameterset>
```

Also: The module "planCalcroute" in your config.xml should be named `planscalcroute`. And add the parameter `clearDefaultTeleportedModeParams` to it:

```xml
<module name="planscalcroute">
  <param name="networkModes" value="walk"/>
  <param name="clearDefaultTeleportedModeParams" value="true" />
</module>
```

---

finally: you might have to make sure that your pedestrians don't run with 60km/h along the roads because they think they are vehicles on a road...

**Comment by TanYun-1** [comment]
@mrieser Thank you very much for your reply. 
I have modified the config file and network file according to your suggestion, and it can run successfully.

But I still have two problems:
 First, after 6 iterations, the results of the run show that traveldistancestatsleds remains the same. I don't know if it's because the only allowed mode is walk or I have set  parameters wrong?

 Second, only 6 iterations are possible now, I was going to set 50 iterations, but got an error.

Hope to get your reply again, thank you!

![traveldistancestatslegs](https://github.com/matsim-org/matsim-code-examples/assets/134666360/260dd917-95ae-4823-8616-463c6be6d24b)
[logfile.log](https://github.com/matsim-org/matsim-code-examples/files/11580970/logfile.log)
[config&plan&network.zip](https://github.com/matsim-org/matsim-code-examples/files/11580971/config.plan.network.zip)

**Comment by mrieser** [comment]
you are testing with the equal network. All alternative routes in the equal network have the same distance. Thus the Leg Travel distance stats always show the same length for all iterations.

Regarding the error: You are still using MATSim 13.0. Please update to a newer version. With MATSim 15.0 I was able to run 10 iterations without errors.

**Comment by TanYun-1** [comment]
@mrieser  I don't understand what is equal network. Can you tell me briefly? Thanks!

I modified the "capacity", "freespeed" and "permlanes" parameters in the network file to keep them inconsistent  and modified  the travel time of each traveler is different in the plan file ,but the running results show that the distance after each iteration is still the same.  

In addition, what puzzles me is that before the modes is set to car, there are no above problems, and it can run with good results, but now there are too many problems when the modes is only set to walk.

**Comment by mrieser** [comment]
> I don't understand what is equal network. Can you tell me briefly?

My mistake, I thought you used one of the example networks provided with MATSim which is called `equil` (short for equilibrium).

>  but now there are too many problems when the modes is only set to walk.

Well, as mentioned in the beginning: MATSim was not designed to simulate walk on the network. So you do this on your own risk.

**Comment by TanYun-1** [comment]
Thank you very much for your reply, it helped me with my research. Next I will try to fix the error or consider using other software. Thanks!
