### ISSUE TITLE
parallelMATSim on linux cluster

### ISSUE THREAD

**Issue by alainT2** [matsim-org/matsim-code-examples#98]
Dear community,

Can I have more informations on How to run parallelMATSIM on a Linux cluster? 
or a version of MATSim on a Linux cluster?

I have been reading the following link (https://github.com/matsim-org/parallelMATSim)  but yet I still do not know how to proceed.

Thank you for your time and consideration and looking forward to hearing from you.

Alain

**Comment by kainagel** [comment]
I put a bit more info into the readme.md of that repo.  Unfortunately, far away from being useable.  If you want to work on the parallel implementation, pls let me know and I will provide a bit more help.

**Comment by jiao1997** [comment]
> I put a bit more info into the readme.md of that repo. Unfortunately, far away from being useable. If you want to work on the parallel implementation, pls let me know and I will provide a bit more help.

Dear kai，
      I am working parallel implementation recently, and I have run your example from link  (https://github.com/matsim-org/parallelMATSim)  successfully. 
     Unfortunately, the simulation didn't speed up. It seems that the parallelmatsim is not a completed project.
       I'm interested in this aspect, could you please give me a little help. Where should I find other information on parallelmatsim?
       Best wishes! 
                                                                                                                                          Yours Sincerely,
                                                                                                                                           Wang

**Comment by kainagel** [comment]
Dear Wang, 

did you use it together with the `parallelMatsim` branch from the matsim main repo?

it is quite far from being a finished project.  Scaling is not the issue now; at this point it plain does not work. The technology is described here: http://www.strc.ch/2003/cetin.pdf (or maybe the full phd thesis here: https://svn.vsp.tu-berlin.de/repos/public-svn/publications/vspwp/2005/05-03/).  Evidently, what we have now is written in Java instead of in C, and it is hugely more complex.  So this would not be an easy exercise.  If I personally had time (which I don't :-( ), I would try as follows:
1. I would first try to make that example (parallelMATSim repo together with parallelMatsim branch of matsim main repo, using the equil scenario and only 2CPNs) work.
2. I seem to remember that the main thing that was missing was the events processing.  Here, one needs a good idea and probably some research, possibly to be done with some illustrative version first.  I would assume that at the end all CPNs want to compute routes.  This means that all CPNs need to catch all events.  So we would need some architecture where all CPNs send the events from the geographical tiles they are responsible for to all other CPNs.  Now, evidently, this does not feel very scalable.  Hm.
3. Serialization currently is just using the Java version; it should be replaced by something faster.

I think that @mrieser and @rodrigo-bruno have worked on 2. and 3., but I don't know how close they were to some drop-in replacement.  They have also worked on an alternative to parts of the MATSim system; again, I don't know how close they are to a drop-in replacement.

Best wishes, Kai

**Comment by jiao1997** [comment]
> Dear Wang,
> 
> did you use it together with the `parallelMatsim` branch from the matsim main repo?
> 
> it is quite far from being a finished project. Scaling is not the issue now; at this point it plain does not work. The technology is described here: http://www.strc.ch/2003/cetin.pdf (or maybe the full phd thesis here: https://svn.vsp.tu-berlin.de/repos/public-svn/publications/vspwp/2005/05-03/). Evidently, what we have now is written in Java instead of in C, and it is hugely more complex. So this would not be an easy exercise. If I personally had time (which I don't :-( ), I would try as follows:
> 
> 1. I would first try to make that example (parallelMATSim repo together with parallelMatsim branch of matsim main repo, using the equil scenario and only 2CPNs) work.
> 2. I seem to remember that the main thing that was missing was the events processing.  Here, one needs a good idea and probably some research, possibly to be done with some illustrative version first.  I would assume that at the end all CPNs want to compute routes.  This means that all CPNs need to catch all events.  So we would need some architecture where all CPNs send the events from the geographical tiles they are responsible for to all other CPNs.  Now, evidently, this does not feel very scalable.  Hm.
> 3. Serialization currently is just using the Java version; it should be replaced by something faster.
> 
> I think that @mrieser and @rodrigo-bruno have worked on 2. and 3., but I don't know how close they were to some drop-in replacement. They have also worked on an alternative to parts of the MATSim system; again, I don't know how close they are to a drop-in replacement.
> 
> Best wishes, Kai

Dear Kai,
         I have download the  parallelMatsim branch from the matsim main repo and import it to eclipse, but there are some mistakes in the QSimProvider class from org.matsim.core.mosim.qsim package.The errors is shown in the following picture:
![image](https://user-images.githubusercontent.com/35290093/69205894-36bb7700-0b86-11ea-97c7-b7aa27e5460d.png)
       Erros: Type mismatch: from Stream < Object > into the < unknown > QSimProvider. Java/matsim/SRC/main/Java/org/matsim/core/mobsim qsim line 107 Java problem. I wonder if my JAVA version caused the problem? which version should I use. Hope to get your early reply.
     Best wishes,
                                                                                                                            Yours Sincerely,
                                                                                                                             Wang

**Comment by rodrigo-bruno** [comment]
> 3. Serialization currently is just using the Java version; it should be replaced by something faster.
> 
> I think that @mrieser and @rodrigo-bruno have worked on 2. and 3., but I don't know how close they were to some drop-in replacement. They have also worked on an alternative to parts of the MATSim system; again, I don't know how close they are to a drop-in replacement.
> 
> Best wishes, Kai

Dear all,

I am currently working with a PhD student (here at ETHZ)  to come up with a faster Java serialization approach that could be used in the project. However, this is still not ready and might take several more weeks to finish.

best,
rodrigo
